using System.Runtime.CompilerServices;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Formatting;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
using static MrKWatkins.OakCpu.CodeGenerator.CommonSyntax;

namespace MrKWatkins.OakCpu.CodeGenerator.Generators;

[SuppressMessage("ReSharper", "InconsistentNaming")]
public abstract partial class TypeGenerator : Generator
{
    public sealed record GeneratedFile(string FileName, string Source);

    private const string FileHeader = """
                                      //------------------------------------------------------------------------------
                                      // <auto-generated>
                                      //     This code was generated by a tool.
                                      //
                                      //     Changes to this file may cause incorrect behaviour and will be lost if
                                      //     the code is regenerated.
                                      // </auto-generated>
                                      //------------------------------------------------------------------------------
                                      #nullable enable

                                      """;

    [GeneratedRegex(@"\r?\n\r?\n\r?\n")]
    private static partial Regex DoubleBlankLinesRegex();

    [GeneratedRegex(@"{\r?\n\r?\n")]
    private static partial Regex ExtraBlankLineInClassDeclarationRegex();

    [GeneratedRegex(@"\r?\n")]
    private static partial Regex NewlineRegex();

    protected const string EmulatorFieldName = "emulator";

    private protected TypeGenerator()
    {
    }

    public static readonly IReadOnlyList<TypeGenerator> AllGenerators = [
        ActionRequiredGenerator.Instance,
        EmulatorInstanceDataMembersAndConstructorGenerator.Instance,
        EmulatorInterruptsGenerator.Instance,
        InstructionEmulatorStateGenerator.Instance,
        InstructionEmulatorInterruptsGenerator.Instance,
        InstructionEmulatorGenerator.Instance,
        InstructionEmulatorResetGenerator.Instance,
        InstructionEmulatorTablesGenerator.Instance,
        EmulatorOverlapsGenerator.Instance,
        EmulatorResetGenerator.Instance,
        EmulatorSerializationGenerator.Instance,
        EmulatorStepsInitializationGenerator.Instance,
        EmulatorStepsGenerator.Instance,
        FlagsClassGenerator.Instance,
        InterruptsClassGenerator.Instance,
        StepStructGenerator.Instance,
        RegistersClassesGenerator.Instance];

    [Pure]
    public string GetFileName(GeneratorContext context) => $"{GetBaseFileName(context)}.generated.cs";

    [Pure]
    protected abstract string GetBaseFileName(GeneratorContext context);

    [Pure]
    public virtual IReadOnlyList<GeneratedFile> GenerateFiles(GeneratorContext context) => [new(GetFileName(context), Generate(context))];

    [Pure]
    public string Generate(GeneratorContext context)
    {
        var compilationUnit = GenerateCompilationUnit(context);
        return Generate(compilationUnit);
    }

    [Pure]
    protected static string Generate(CompilationUnitSyntax compilationUnit)
    {

        using var workspace = new AdhocWorkspace();

        // This will lay out properties and methods correctly.
        var formatted = Formatter.Format(compilationUnit, workspace);

        // Add extra spacing where needed.
        var spaced = new ExtraSpacingRewriter().Visit(formatted);

        var code = spaced.ToFullString();

        // A final tidy that is much easier to do with regex than modifying the syntax tree.
        var tidied = NormalizeLineEndings(code);

        return FileHeader + tidied;
    }

    [Pure]
    private static string NormalizeLineEndings(string code)
    {
        // Remove double new blank lines.
        code = DoubleBlankLinesRegex().Replace(code, "\n\n");

        // Remove extra blank line in class declaration.
        code = ExtraBlankLineInClassDeclarationRegex().Replace(code, "{\n");

        // Normalize new lines.
        code = NewlineRegex().Replace(code, Environment.NewLine);

        return code;
    }

    [Pure]
    public CompilationUnitSyntax GenerateCompilationUnit(GeneratorContext context)
    {
        context = context.WithRequiredUsings();

        return GenerateCompilationUnit(context, CreateTypes(context));
    }

    [MustUseReturnValue]
    protected virtual IEnumerable<BaseTypeDeclarationSyntax> CreateTypes(GeneratorContext context)
    {
        yield return CreateType(context);
    }

    [MustUseReturnValue]
    protected virtual BaseTypeDeclarationSyntax CreateType(GeneratorContext context)
    {
        throw new NotImplementedException($"{nameof(CreateType)} is not implemented and {nameof(CreateTypes)} has not been overridden.");
    }

    [Pure]
    protected static PropertyDeclarationSyntax CreateGetOnlyProperty(GeneratorContext context, string typeName, string propertyName) =>
        CreateGetOnlyProperty(context, IdentifierName(typeName), propertyName, TokenList(Public));

    [Pure]
    protected static PropertyDeclarationSyntax CreateGetOnlyProperty(GeneratorContext context, TypeSyntax type, string propertyName, SyntaxTokenList modifiers) =>
        PropertyDeclaration(type, Identifier(propertyName))
            .WithModifiers(modifiers)
            .WithAccessorList(
                AccessorList(
                [
                    AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                        .WithAttributeLists([AttributeList([CreateMethodImplAttribute(context.RequiredUsings, MethodImplOptions.AggressiveInlining)])])
                        .WithSemicolonToken(Semicolon)
                ]));

    [Pure]
    protected static PropertyDeclarationSyntax CreateAbstractGetOnlyProperty(TypeSyntax type, string propertyName) =>
        PropertyDeclaration(type, Identifier(propertyName))
            .WithModifiers(TokenList(Public, Abstract))
            .WithAccessorList(
                AccessorList(
                [
                    AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                        .WithSemicolonToken(Semicolon)
                ]));

    [Pure]
    protected static PropertyDeclarationSyntax CreateGetSetProperty(GeneratorContext context, TypeSyntax type, string propertyName, ExpressionSyntax getExpression, ExpressionSyntax setExpression) =>
        CreateGetSetProperty(context, type, propertyName, getExpression, setExpression, TokenList(Public));

    [Pure]
    protected static PropertyDeclarationSyntax CreateGetSetProperty(GeneratorContext context, TypeSyntax type, string propertyName, ExpressionSyntax getExpression, ExpressionSyntax setExpression, SyntaxTokenList modifiers) =>
        PropertyDeclaration(type, Identifier(propertyName))
            .WithModifiers(modifiers)
            .WithAccessorList(
                AccessorList(List(
                [
                    AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                        .WithExpressionBody(ArrowExpressionClause(getExpression))
                        .WithAttributeLists([AttributeList([CreateMethodImplAttribute(context.RequiredUsings, MethodImplOptions.AggressiveInlining)])])
                        .WithSemicolonToken(Token(SyntaxKind.SemicolonToken)),

                    AccessorDeclaration(SyntaxKind.SetAccessorDeclaration)
                        .WithExpressionBody(ArrowExpressionClause(setExpression))
                        .WithAttributeLists([AttributeList([CreateMethodImplAttribute(context.RequiredUsings, MethodImplOptions.AggressiveInlining)])])
                        .WithSemicolonToken(Token(SyntaxKind.SemicolonToken))
                ])));

    [Pure]
    protected static PropertyDeclarationSyntax CreateAbstractGetSetProperty(TypeSyntax type, string propertyName) =>
        PropertyDeclaration(type, Identifier(propertyName))
            .WithModifiers(TokenList(Public, Abstract))
            .WithAccessorList(
                AccessorList(
                [
                    AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                        .WithSemicolonToken(Semicolon),

                    AccessorDeclaration(SyntaxKind.SetAccessorDeclaration)
                        .WithSemicolonToken(Semicolon)
                ]));

    [Pure]
    protected static PropertyDeclarationSyntax CreateOverrideGetSetProperty(GeneratorContext context, TypeSyntax type, string propertyName, ExpressionSyntax getExpression, ExpressionSyntax setExpression) =>
        CreateGetSetProperty(context, type, propertyName, getExpression, setExpression, TokenList(Public, Override));

    [Pure]
    protected static FieldDeclarationSyntax CreateEmulatorField(TypeSyntax emulatorType) =>
        FieldDeclaration(
                VariableDeclaration(emulatorType)
                    .WithVariables(SingletonSeparatedList(VariableDeclarator(Identifier(EmulatorFieldName)))))
            .WithModifiers(TokenList(Private, ReadOnly));
    [Pure]
    protected static string GetEmulatorClassName(GeneratorContext context) => $"{context.Cpu.Name}StepEmulator";

    [Pure]
    protected static IdentifierNameSyntax GetEmulatorClassIdentifier(GeneratorContext context) => IdentifierName(GetEmulatorClassName(context));

    [Pure]
    protected static string GetInstructionEmulatorClassName(GeneratorContext context) => $"{context.Cpu.Name}InstructionEmulator";

    [Pure]
    protected static IdentifierNameSyntax GetInstructionEmulatorClassIdentifier(GeneratorContext context) => IdentifierName(GetInstructionEmulatorClassName(context));

    [Pure]
    protected static ParameterSyntax CreateInstructionEmulatorParameter(GeneratorContext context) => Parameter(Identifier(EmulatorParameterName)).WithType(GetInstructionEmulatorClassIdentifier(context));

    [Pure]
    protected static FunctionPointerTypeSyntax CreateInstructionHandlerType(GeneratorContext context) =>
        FunctionPointerType(
            null,
            FunctionPointerParameterList(
            [
                FunctionPointerParameter(IdentifierName(GetInstructionEmulatorClassName(context))),
                FunctionPointerParameter(
                    GenericName(Identifier("Action"))
                        .WithTypeArgumentList(
                            TypeArgumentList(
                                SeparatedList<TypeSyntax>(
                                [
                                    IdentifierName(ActionRequiredEnumName),
                                    Token(SyntaxKind.CommaToken),
                                    UShortType,
                                    Token(SyntaxKind.CommaToken),
                                    ByteType
                                ])))),
                FunctionPointerParameter(IntType)
            ]));

    [Pure]
    protected static string GetRegistersClassName(GeneratorContext context, string? category = null) => $"{context.Cpu.Name}{category}Registers";

    [Pure]
    protected static string GetStepRegistersClassName(GeneratorContext context, string? category = null) => $"{context.Cpu.Name}Step{category}Registers";

    [Pure]
    protected static string GetInstructionRegistersClassName(GeneratorContext context, string? category = null) => $"{context.Cpu.Name}Instruction{category}Registers";

    [Pure]
    protected static string GetFlagsClassName(GeneratorContext context) => $"{context.Cpu.Name}Flags";

    [Pure]
    protected static string GetStepFlagsClassName(GeneratorContext context) => $"{context.Cpu.Name}StepFlags";

    [Pure]
    protected static string GetInstructionFlagsClassName(GeneratorContext context) => $"{context.Cpu.Name}InstructionFlags";

    [Pure]
    protected static string GetInterruptsClassName(GeneratorContext context) => $"{context.Cpu.Name}Interrupts";

    [Pure]
    protected static string GetStepInterruptsClassName(GeneratorContext context) => $"{context.Cpu.Name}StepInterrupts";

    [Pure]
    protected static string GetInstructionInterruptsClassName(GeneratorContext context) => $"{context.Cpu.Name}InstructionInterrupts";

    [Pure]
    protected static FunctionPointerTypeSyntax CreateOverlapHandlerType(GeneratorContext context) =>
        FunctionPointerType(
            null,
            FunctionPointerParameterList(
            [
                FunctionPointerParameter(IdentifierName(GetEmulatorClassName(context))),
                FunctionPointerParameter(VoidType)
            ]));

    [Pure]
    protected IReadOnlyList<GeneratedFile> GenerateOneFilePerType(GeneratorContext context)
    {
        context = context.WithRequiredUsings();
        var types = CreateTypes(context).ToList();

        return types
            .Select(type => new GeneratedFile($"{type.Identifier.ValueText}.generated.cs", Generate(GenerateCompilationUnit(context, [type]))))
            .ToList();
    }

    [Pure]
    private static CompilationUnitSyntax GenerateCompilationUnit(GeneratorContext context, IEnumerable<BaseTypeDeclarationSyntax> types)
    {
        var members = new List<MemberDeclarationSyntax> { context.CreateRootNamespaceDeclaration() };
        members.AddRange(types);

        return CompilationUnit()
            .AddUsings(context.RequiredUsings.OrderBy(n => n).Select(CreateUsingStatement).ToArray())
            .AddMembers(members.ToArray())
            .NormalizeWhitespace();
    }

    [Pure]
    private static UsingDirectiveSyntax CreateUsingStatement(string @namespace) => UsingDirective(IdentifierName(@namespace));
}