//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace MrKWatkins.OakCpu.Z80;
/// <summary>
/// Handles the external bus actions requested by the Z80InstructionEmulator.
/// </summary>
public interface IZ80BusHandler
{
    /// <summary>
    /// Performs the external bus action required for the current CPU cycle.
    /// </summary>
    /// <param name="actionRequired">
    /// The action the host must perform.
    /// </param>
    /// <param name="address">
    /// The address on the external bus.
    /// </param>
    /// <param name="data">
    /// The data on the external bus for write actions; ignored for reads.
    /// </param>
    void OnActionRequired(ActionRequired actionRequired, ushort address, byte data);
}
