//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MrKWatkins.OakCpu.Z80;

public sealed unsafe partial class Z80Emulator
{
    private static readonly ushort[] InterruptModeStepTable = [12, 17, 29];

    private static bool HandleInterrupts(Z80Emulator emulator, ref ActionRequired actionRequired)
    {
        if (emulator.interrupt && emulator.iff1)
        {
            emulator.halted = false;
            emulator.currentStep = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(InterruptModeStepTable), emulator.im);
            emulator.interrupt = false;
            actionRequired = ActionRequired.None;
            return true;
        }

        emulator.interrupt = false;
        return false;
    }
}
