//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MrKWatkins.OakCpu.Z80;

public sealed unsafe partial class Z80Emulator
{
    private static bool HandleInterrupts(Z80Emulator emulator, ref ActionRequired actionRequired)
    {
        if (emulator.interrupt)
        {
            emulator.interrupt = false;
            if (emulator.iff1)
            {
                emulator.halted = false;
                // Move to interrupt mode.
                emulator.currentStep = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(InterruptModeStepTable), emulator.im);
                actionRequired = ActionRequired.None;
                return true;
            }
        }

        return false;
    }
}
