//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.IO;

namespace MrKWatkins.OakCpu.Z80;

public sealed unsafe partial class Z80InstructionEmulator
{
    /// <summary>
    /// The number of bytes required to serialize the emulator state.
    /// </summary>
    public const int SerializedSize = 41;

    /// <summary>
    /// Serializes this emulator's Z80 CPU state.
    /// </summary>
    /// <param name="destination">
    /// The destination span to write the CPU state to.
    /// </param>
    public void Serialize(Span<byte> destination)
    {
        if (destination.Length < SerializedSize)
        {
            throw new ArgumentException("The destination span is too small.", nameof(destination));
        }

        if (opcodeStepTable == OpcodeStepTableNoPrefix)
        {
            destination[0] = (byte)0;
        }
        else if (opcodeStepTable == OpcodeStepTablePrefixCB)
        {
            destination[0] = (byte)1;
        }
        else if (opcodeStepTable == OpcodeStepTablePrefixDD)
        {
            destination[0] = (byte)2;
        }
        else if (opcodeStepTable == OpcodeStepTablePrefixED)
        {
            destination[0] = (byte)3;
        }
        else if (opcodeStepTable == OpcodeStepTablePrefixFD)
        {
            destination[0] = (byte)4;
        }
        else if (opcodeStepTable == OpcodeStepTableDDCB)
        {
            destination[0] = (byte)5;
        }
        else if (opcodeStepTable == OpcodeStepTableFDCB)
        {
            destination[0] = (byte)6;
        }
        else
        {
            throw new InvalidOperationException("Unknown opcode step table.");
        }

        fixed (byte* block0 = &F)
        {
            new ReadOnlySpan<byte>((byte*)block0, 40).CopyTo(destination.Slice(1, 40));
        }
    }

    /// <summary>
    /// Serializes this emulator's Z80 CPU state.
    /// </summary>
    /// <param name="stream">
    /// The stream to write the CPU state to.
    /// </param>
    public void Serialize(Stream stream)
    {
        Span<byte> buffer = stackalloc byte[SerializedSize];
        Serialize(buffer);
        stream.Write(buffer);
    }

    /// <summary>
    /// Deserializes a Z80 CPU state.
    /// </summary>
    /// <param name="source">
    /// The serialized CPU state to read from.
    /// </param>
    /// <returns>
    /// The deserialized Z80 emulator.
    /// </returns>
    public static Z80InstructionEmulator Deserialize(ReadOnlySpan<byte> source)
    {
        var deserialized = new Z80InstructionEmulator();
        deserialized.Restore(source);
        return deserialized;
    }

    /// <summary>
    /// Deserializes a Z80 CPU state.
    /// </summary>
    /// <param name="stream">
    /// The stream to read the CPU state from.
    /// </param>
    /// <returns>
    /// The deserialized Z80 emulator.
    /// </returns>
    public static Z80InstructionEmulator Deserialize(Stream stream)
    {
        Span<byte> buffer = stackalloc byte[SerializedSize];
        stream.ReadExactly(buffer);
        return Deserialize(buffer);
    }

    /// <summary>
    /// Restores this emulator from a serialized Z80 CPU state.
    /// </summary>
    /// <param name="source">
    /// The serialized CPU state to read from.
    /// </param>
    public void Restore(ReadOnlySpan<byte> source)
    {
        if (source.Length < SerializedSize)
        {
            throw new ArgumentException("The source span is too small.", nameof(source));
        }

        opcodeStepTable = source[0] switch
        {
            0 => OpcodeStepTableNoPrefix,
            1 => OpcodeStepTablePrefixCB,
            2 => OpcodeStepTablePrefixDD,
            3 => OpcodeStepTablePrefixED,
            4 => OpcodeStepTablePrefixFD,
            5 => OpcodeStepTableDDCB,
            6 => OpcodeStepTableFDCB,
            _ => throw new InvalidOperationException("Unknown opcode step table.")
        };
        fixed (byte* block0 = &F)
        {
            source.Slice(1, 40).CopyTo(new Span<byte>((byte*)block0, 40));
        }
    }

    /// <summary>
    /// Restores this emulator from a serialized Z80 CPU state.
    /// </summary>
    /// <param name="stream">
    /// The stream to read the CPU state from.
    /// </param>
    public void Restore(Stream stream)
    {
        Span<byte> buffer = stackalloc byte[SerializedSize];
        stream.ReadExactly(buffer);
        Restore(buffer);
    }
}
