//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.CompilerServices;

namespace MrKWatkins.OakCpu.Z80
{
    public sealed class Z80Interrupts
    {
        private readonly Z80Emulator emulator;

        internal Z80Interrupts(Z80Emulator emulator)
        {
            this.emulator = emulator;
        }

        public bool Halted
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => emulator.halted; 
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set => emulator.halted = value;
        }

        public bool IFF1
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => emulator.iff1; 
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set => emulator.iff1 = value;
        }

        public bool IFF2
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => emulator.iff2; 
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set => emulator.iff2 = value;
        }

        public byte IM
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => emulator.im; 
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set => emulator.im = value;
        }

        public bool Interrupt
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => emulator.interrupt; 
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set => emulator.interrupt = value;
        }
    }
}
