//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MrKWatkins.OakCpu.Z80;

public sealed unsafe partial class Z80InstructionEmulator
{
    private static bool HandleInterrupts(Z80InstructionEmulator emulator)
    {
        if (emulator.interrupt)
        {
            emulator.interrupt = false;
            if (emulator.iff1)
            {
                emulator.halted = false;
                // Queue interrupt mode interrupt.
                emulator.QueueInterrupt(Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(InterruptModeStepTable), emulator.im));
                return true;
            }
        }

        return false;
    }
}
