//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MrKWatkins.OakCpu.Z80;
/// <summary>
/// Represents a Z80 emulator that executes one complete instruction at a time.
/// </summary>
[StructLayout(LayoutKind.Explicit)]
public sealed unsafe partial class Z80InstructionEmulator
{
    [FieldOffset(0)]
    internal ushort AF;

    [FieldOffset(0)]
    internal byte F;

    [FieldOffset(1)]
    internal byte A;

    [FieldOffset(2)]
    internal ushort BC;

    [FieldOffset(2)]
    internal byte C;

    [FieldOffset(3)]
    internal byte B;

    [FieldOffset(4)]
    internal ushort DE;

    [FieldOffset(4)]
    internal byte E;

    [FieldOffset(5)]
    internal byte D;

    [FieldOffset(6)]
    internal ushort HL;

    [FieldOffset(6)]
    internal byte L;

    [FieldOffset(7)]
    internal byte H;

    [FieldOffset(8)]
    internal ushort IR;

    [FieldOffset(8)]
    internal byte R;

    [FieldOffset(9)]
    internal byte I;

    [FieldOffset(10)]
    internal ushort IX;

    [FieldOffset(10)]
    internal byte IXL;

    [FieldOffset(11)]
    internal byte IXH;

    [FieldOffset(12)]
    internal ushort IY;

    [FieldOffset(12)]
    internal byte IYL;

    [FieldOffset(13)]
    internal byte IYH;

    [FieldOffset(14)]
    internal ushort PC;

    [FieldOffset(14)]
    internal byte PCL;

    [FieldOffset(15)]
    internal byte PCH;

    [FieldOffset(16)]
    internal ushort SP;

    [FieldOffset(16)]
    internal byte SPL;

    [FieldOffset(17)]
    internal byte SPH;

    [FieldOffset(18)]
    internal ushort WZ;

    [FieldOffset(18)]
    internal byte Z;

    [FieldOffset(19)]
    internal byte W;

    [FieldOffset(20)]
    internal ushort Shadow_AF;

    [FieldOffset(20)]
    internal byte Shadow_AFL;

    [FieldOffset(21)]
    internal byte Shadow_AFH;

    [FieldOffset(22)]
    internal ushort Shadow_BC;

    [FieldOffset(22)]
    internal byte Shadow_BCL;

    [FieldOffset(23)]
    internal byte Shadow_BCH;

    [FieldOffset(24)]
    internal ushort Shadow_DE;

    [FieldOffset(24)]
    internal byte Shadow_DEL;

    [FieldOffset(25)]
    internal byte Shadow_DEH;

    [FieldOffset(26)]
    internal ushort Shadow_HL;

    [FieldOffset(26)]
    internal byte Shadow_HLL;

    [FieldOffset(27)]
    internal byte Shadow_HLH;

    [FieldOffset(28)]
    internal byte Q;

    internal const ushort NoNextSequenceStep = ushort.MaxValue;

    /// <summary>
    /// Initializes a new Z80InstructionEmulator instance.
    /// </summary>
    public Z80InstructionEmulator()
    {
        opcodeStepTable = OpcodeStepTableNoPrefix;
        nextSequenceStep = NoNextSequenceStep;
        Registers = new Z80InstructionRegisters(this);
        Flags = new Z80InstructionFlags(this);
        Interrupts = new Z80InstructionInterrupts(this);
    }

    [FieldOffset(29)]
    private ushort address;

    /// <summary>
    /// Gets the address for the current external bus action.
    /// </summary>
    public ushort Address
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => address;
    }

    [FieldOffset(31)]
    private byte latch;

    [FieldOffset(32)]
    internal byte im;

    [FieldOffset(33)]
    internal bool iff1;

    [FieldOffset(34)]
    internal bool iff2;

    [FieldOffset(35)]
    internal bool halted;

    [FieldOffset(36)]
    internal bool interrupt;

    [FieldOffset(37)]
    private byte data;

    /// <summary>
    /// Gets or sets the data value for the current external bus action.
    /// </summary>
    public byte Data
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => data; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => data = value;
    }

    [FieldOffset(38)]
    internal ushort nextSequenceStep;

    /// <summary>
    /// Gets the Z80 registers.
    /// </summary>
    [field: FieldOffset(40)]
    public Z80Registers Registers
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get;
    }

    /// <summary>
    /// Gets the Z80 flags.
    /// </summary>
    [field: FieldOffset(48)]
    public Z80Flags Flags
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get;
    }

    /// <summary>
    /// Gets the Z80 interrupt state.
    /// </summary>
    [field: FieldOffset(56)]
    public Z80Interrupts Interrupts
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get;
    }

    [FieldOffset(64)]
    private ushort[] opcodeStepTable;

    /// <summary>
    /// Executes one complete instruction or scheduled sequence.
    /// </summary>
    /// <param name="handler">
    /// Handles the external bus actions required to execute the instruction.
    /// </param>
    /// <returns>
    /// The number of T-states executed.
    /// </returns>
    public int ExecuteInstruction<THandler>(ref THandler handler)
        where THandler : IZ80BusHandler, allows ref struct
    {
        ushort scheduledSequenceStep = nextSequenceStep;
        if (scheduledSequenceStep != NoNextSequenceStep)
        {
            nextSequenceStep = NoNextSequenceStep;
            return ExecuteDecodedInstruction(scheduledSequenceStep, ref handler);
        }

        return ExecuteDecodedInstruction(OpcodeReadStep0, ref handler);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private int ExecuteDecodedInstruction<THandler>(ushort decodedStep, ref THandler handler)
        where THandler : IZ80BusHandler, allows ref struct
    {
        var instruction = Dispatch<THandler>.Instructions[decodedStep];
        return instruction(this, ref handler);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private int CompleteInstruction(bool instructionUpdatesFlags, int tStates)
    {
        var emulator = this;
        if (instructionUpdatesFlags)
        {
            emulator.Q = emulator.F;
        }
        else
        {
            emulator.Q = 0x00;
        }

        HandleInterrupts(emulator);
        return tStates;
    }
}
