//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;

namespace MrKWatkins.OakCpu.Z80;

internal sealed class Z80InstructionShadowRegisters : Z80ShadowRegisters
{
    private readonly Z80InstructionEmulator emulator;

    internal Z80InstructionShadowRegisters(Z80InstructionEmulator emulator)
    {
        this.emulator = emulator;
    }

    public override ushort AF
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.Shadow_AF; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.Shadow_AF = value;
    }

    public override ushort BC
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.Shadow_BC; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.Shadow_BC = value;
    }

    public override ushort DE
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.Shadow_DE; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.Shadow_DE = value;
    }

    public override ushort HL
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.Shadow_HL; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.Shadow_HL = value;
    }
}
