//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;

namespace MrKWatkins.OakCpu.Z80;

internal sealed class Z80InstructionRegisters : Z80Registers
{
    private readonly Z80InstructionEmulator emulator;

    internal Z80InstructionRegisters(Z80InstructionEmulator emulator) : base(new Z80InstructionShadowRegisters(emulator))
    {
        this.emulator = emulator;
    }

    public override byte A
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.A; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.A = value;
    }

    public override ushort AF
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.AF; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.AF = value;
    }

    public override byte B
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.B; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.B = value;
    }

    public override ushort BC
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.BC; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.BC = value;
    }

    public override byte C
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.C; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.C = value;
    }

    public override byte D
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.D; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.D = value;
    }

    public override ushort DE
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.DE; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.DE = value;
    }

    public override byte E
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.E; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.E = value;
    }

    public override byte F
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.F; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.F = value;
    }

    public override byte H
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.H; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.H = value;
    }

    public override ushort HL
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.HL; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.HL = value;
    }

    public override byte I
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.I; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.I = value;
    }

    public override ushort IR
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.IR; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.IR = value;
    }

    public override ushort IX
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.IX; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.IX = value;
    }

    public override byte IXH
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.IXH; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.IXH = value;
    }

    public override byte IXL
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.IXL; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.IXL = value;
    }

    public override ushort IY
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.IY; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.IY = value;
    }

    public override byte IYH
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.IYH; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.IYH = value;
    }

    public override byte IYL
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.IYL; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.IYL = value;
    }

    public override byte L
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.L; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.L = value;
    }

    public override ushort PC
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.PC; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.PC = value;
    }

    public override byte Q
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.Q; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.Q = value;
    }

    public override byte R
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.R; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.R = value;
    }

    public override ushort SP
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.SP; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.SP = value;
    }

    public override byte W
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.W; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.W = value;
    }

    public override ushort WZ
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.WZ; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.WZ = value;
    }

    public override byte Z
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.Z; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.Z = value;
    }
}
