//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;

namespace MrKWatkins.OakCpu.Z80;
/// <inheritdoc/>
public sealed class Z80InstructionInterrupts : Z80Interrupts
{
    private readonly Z80InstructionEmulator emulator;

    internal Z80InstructionInterrupts(Z80InstructionEmulator emulator)
    {
        this.emulator = emulator;
    }

    /// <inheritdoc/>
    public override bool Halted
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.halted;
        set
        {
            emulator.halted = value;
            emulator.nextSequenceStep = value ? (ushort)5 : emulator.nextSequenceStep == (ushort)5 ? Z80InstructionEmulator.NoNextSequenceStep : emulator.nextSequenceStep;
        }
    }

    /// <inheritdoc/>
    public override bool IFF1
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.iff1; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.iff1 = value;
    }

    /// <inheritdoc/>
    public override bool IFF2
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.iff2; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.iff2 = value;
    }

    /// <inheritdoc/>
    public override byte IM
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.im; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.im = value;
    }

    /// <inheritdoc/>
    public override bool Interrupt
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.interrupt; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.interrupt = value;
    }
}
