//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;

namespace MrKWatkins.OakCpu.Z80;

public abstract class Z80Registers
{
    protected Z80Registers(Z80ShadowRegisters shadow)
    {
        Shadow = shadow;
    }

    public Z80ShadowRegisters Shadow
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get;
    }

    public abstract byte A { get; set; }

    public abstract ushort AF { get; set; }

    public abstract byte B { get; set; }

    public abstract ushort BC { get; set; }

    public abstract byte C { get; set; }

    public abstract byte D { get; set; }

    public abstract ushort DE { get; set; }

    public abstract byte E { get; set; }

    public abstract byte F { get; set; }

    public abstract byte H { get; set; }

    public abstract ushort HL { get; set; }

    public abstract byte I { get; set; }

    public abstract ushort IR { get; set; }

    public abstract ushort IX { get; set; }

    public abstract byte IXH { get; set; }

    public abstract byte IXL { get; set; }

    public abstract ushort IY { get; set; }

    public abstract byte IYH { get; set; }

    public abstract byte IYL { get; set; }

    public abstract byte L { get; set; }

    public abstract ushort PC { get; set; }

    public abstract byte Q { get; set; }

    public abstract byte R { get; set; }

    public abstract ushort SP { get; set; }

    public abstract byte W { get; set; }

    public abstract ushort WZ { get; set; }

    public abstract byte Z { get; set; }
}
