//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;

namespace MrKWatkins.OakCpu.Z80;

public abstract class Z80ShadowRegisters
{
    public abstract ushort AF { get; set; }

    public abstract ushort BC { get; set; }

    public abstract ushort DE { get; set; }

    public abstract ushort HL { get; set; }
}
