//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;

namespace MrKWatkins.OakCpu.Z80;
/// <summary>
/// Provides access to the Z80 shadow registers.
/// </summary>
public abstract class Z80ShadowRegisters
{
    /// <summary>
    /// Gets or sets the shadow AF register pair.
    /// </summary>
    public abstract ushort AF { get; set; }

    /// <summary>
    /// Gets or sets the shadow BC register pair.
    /// </summary>
    public abstract ushort BC { get; set; }

    /// <summary>
    /// Gets or sets the shadow DE register pair.
    /// </summary>
    public abstract ushort DE { get; set; }

    /// <summary>
    /// Gets or sets the shadow HL register pair.
    /// </summary>
    public abstract ushort HL { get; set; }
}
