//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MrKWatkins.OakCpu.Z80;

public sealed unsafe partial class Z80StepEmulator
{
    private static bool HandleInterrupts(Z80StepEmulator emulator, ref ActionRequired actionRequired)
    {
        if (emulator.interrupt & emulator.iff1)
        {
            emulator.halted = false;
            // Move to interrupt mode.
            emulator.currentStep = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(InterruptModeStepTable), emulator.im);
            actionRequired = ActionRequired.None;
            return true;
        }

        return false;
    }
}
