using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Formatting;

namespace MrKWatkins.OakCpu.CodeGenerator;

internal static partial class GeneratedCodeFormatter
{
    private const string FileHeader = """
                                       //------------------------------------------------------------------------------
                                       // <auto-generated>
                                       //     This code was generated by a tool.
                                       //
                                       //     Changes to this file may cause incorrect behaviour and will be lost if
                                       //     the code is regenerated.
                                       // </auto-generated>
                                       //------------------------------------------------------------------------------
                                       #nullable enable

                                       """;

    [GeneratedRegex(@"\r?\n\r?\n\r?\n")]
    private static partial Regex DoubleBlankLinesRegex();

    [GeneratedRegex(@"{\r?\n\r?\n")]
    private static partial Regex ExtraBlankLineInClassDeclarationRegex();

    [GeneratedRegex(@"\r?\n")]
    private static partial Regex NewlineRegex();

    [Pure]
    internal static string Format(CompilationUnitSyntax compilationUnit)
    {
        using var workspace = new AdhocWorkspace();

        // This will lay out properties and methods correctly.
        var formatted = Formatter.Format(compilationUnit, workspace);

        // Add extra spacing where needed.
        var spaced = new ExtraSpacingRewriter().Visit(formatted);

        var code = spaced.ToFullString();

        // A final tidy that is much easier to do with regex than modifying the syntax tree.
        var tidied = NormalizeLineEndings(code);

        return FileHeader + tidied;
    }

    [Pure]
    private static string NormalizeLineEndings(string code)
    {
        // Remove double new blank lines.
        code = DoubleBlankLinesRegex().Replace(code, "\n\n");

        // Remove extra blank line in class declaration.
        code = ExtraBlankLineInClassDeclarationRegex().Replace(code, "{\n");

        // Normalize new lines.
        code = NewlineRegex().Replace(code, Environment.NewLine);

        return code;
    }
}