//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MrKWatkins.OakCpu.M6502;
/// <summary>
/// Represents a M6502 emulator that executes one complete instruction at a time.
/// </summary>
[StructLayout(LayoutKind.Explicit)]
public sealed unsafe partial class M6502InstructionEmulator
{
    [FieldOffset(0)]
    internal ushort PC;

    [FieldOffset(0)]
    internal byte PCL;

    [FieldOffset(1)]
    internal byte PCH;

    [FieldOffset(2)]
    internal byte A;

    [FieldOffset(3)]
    internal byte P;

    [FieldOffset(4)]
    internal byte S;

    [FieldOffset(5)]
    internal byte X;

    [FieldOffset(6)]
    internal byte Y;

    internal const ushort NoNextSequenceStep = ushort.MaxValue;

    /// <summary>
    /// Initializes a new M6502InstructionEmulator instance.
    /// </summary>
    public M6502InstructionEmulator()
    {
        opcodeStepTable = OpcodeStepTableNoPrefix;
        nextSequenceStep = NoNextSequenceStep;
        Registers = new M6502InstructionRegisters(this);
        Flags = new M6502InstructionFlags(this);
        Interrupts = new M6502InstructionInterrupts(this);
    }

    /// <summary>
    /// Gets the M6502 registers.
    /// </summary>
    [field: FieldOffset(8)]
    public M6502Registers Registers
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get;
    }

    /// <summary>
    /// Gets the M6502 flags.
    /// </summary>
    [field: FieldOffset(16)]
    public M6502Flags Flags
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get;
    }

    /// <summary>
    /// Gets the M6502 interrupt state.
    /// </summary>
    [field: FieldOffset(24)]
    public M6502Interrupts Interrupts
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get;
    }

    [FieldOffset(32)]
    private ushort[] opcodeStepTable;

    [FieldOffset(40)]
    private ushort ad;

    [FieldOffset(42)]
    private ushort interruptvector;

    [FieldOffset(44)]
    private ushort address;

    /// <summary>
    /// Gets the address for the current external bus action.
    /// </summary>
    public ushort Address
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => address;
    }

    [FieldOffset(46)]
    private bool pendingnmi;

    [FieldOffset(47)]
    private bool previousnmi;

    [FieldOffset(48)]
    private bool sampledirq;

    [FieldOffset(49)]
    internal bool irq;

    [FieldOffset(50)]
    internal bool nmi;

    [FieldOffset(51)]
    private byte data;

    /// <summary>
    /// Gets or sets the data value for the current external bus action.
    /// </summary>
    public byte Data
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => data; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => data = value;
    }

    [FieldOffset(52)]
    internal ushort nextSequenceStep;

    /// <summary>
    /// Executes one complete instruction or scheduled sequence.
    /// </summary>
    /// <param name="onActionRequired">
    /// Called whenever the emulator requires an external bus action.
    /// </param>
    /// <returns>
    /// The number of T-states executed.
    /// </returns>
    public int ExecuteInstruction(Action<ActionRequired, ushort, byte> onActionRequired)
    {
        ArgumentNullException.ThrowIfNull(onActionRequired);
        ushort scheduledSequenceStep = nextSequenceStep;
        if (scheduledSequenceStep != NoNextSequenceStep)
        {
            nextSequenceStep = NoNextSequenceStep;
            return ExecuteDecodedInstruction(scheduledSequenceStep, onActionRequired);
        }

        return ExecuteDecodedInstruction(OpcodeReadStep0, onActionRequired);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private int ExecuteDecodedInstruction(ushort decodedStep, Action<ActionRequired, ushort, byte> onActionRequired)
    {
        var instruction = Instructions[decodedStep];
        return instruction(this, onActionRequired);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private int CompleteInstruction(bool instructionUpdatesFlags, int tStates)
    {
        var emulator = this;
        return tStates;
    }
}
