//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace MrKWatkins.OakCpu.M6502;

public sealed unsafe partial class M6502InstructionEmulator
{
    /// <summary>
    /// Resets the M6502 CPU state.
    /// </summary>
    public void Reset()
    {
        opcodeStepTable = OpcodeStepTableNoPrefix;
        address = 0;
        data = 0;
        nextSequenceStep = NoNextSequenceStep;
        PC = 0;
        A = 0;
        P = 0;
        S = 0;
        X = 0;
        Y = 0;
    }
}
