//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MrKWatkins.OakCpu.M6502;
/// <summary>
/// Represents a M6502 emulator that executes one complete instruction at a time.
/// </summary>
[StructLayout(LayoutKind.Explicit)]
public sealed unsafe partial class M6502InstructionEmulator
{
    [FieldOffset(0)]
    internal ushort PC;

    [FieldOffset(0)]
    internal byte PCL;

    [FieldOffset(1)]
    internal byte PCH;

    [FieldOffset(2)]
    internal byte A;

    [FieldOffset(3)]
    internal byte P;

    [FieldOffset(4)]
    internal byte S;

    [FieldOffset(5)]
    internal byte X;

    [FieldOffset(6)]
    internal byte Y;

    internal const ushort NoNextSequenceStep = ushort.MaxValue;

    /// <summary>
    /// Initializes a new M6502InstructionEmulator instance.
    /// </summary>
    public M6502InstructionEmulator()
    {
        opcodeStepTable = OpcodeStepTableNoPrefix;
        nextSequenceStep = NoNextSequenceStep;
        Registers = new M6502InstructionRegisters(this);
        Flags = new M6502InstructionFlags(this);
        Interrupts = new M6502InstructionInterrupts(this);
    }

    [FieldOffset(7)]
    private ushort ad;

    [FieldOffset(9)]
    private ushort interruptvector;

    [FieldOffset(11)]
    private ushort address;

    /// <summary>
    /// Gets the address for the current external bus action.
    /// </summary>
    public ushort Address
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => address;
    }

    [FieldOffset(13)]
    private bool pendingnmi;

    [FieldOffset(14)]
    private bool previousnmi;

    [FieldOffset(15)]
    private bool sampledirq;

    [FieldOffset(16)]
    internal bool irq;

    [FieldOffset(17)]
    internal bool nmi;

    [FieldOffset(18)]
    private byte data;

    /// <summary>
    /// Gets or sets the data value for the current external bus action.
    /// </summary>
    public byte Data
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => data; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => data = value;
    }

    [FieldOffset(19)]
    internal ushort nextSequenceStep;

    /// <summary>
    /// Gets the M6502 registers.
    /// </summary>
    [field: FieldOffset(24)]
    public M6502InstructionRegisters Registers
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get;
    }

    /// <summary>
    /// Gets the M6502 flags.
    /// </summary>
    [field: FieldOffset(32)]
    public M6502InstructionFlags Flags
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get;
    }

    /// <summary>
    /// Gets the M6502 interrupt state.
    /// </summary>
    [field: FieldOffset(40)]
    public M6502InstructionInterrupts Interrupts
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get;
    }

    [FieldOffset(48)]
    private ushort[] opcodeStepTable;

    /// <summary>
    /// Executes one complete instruction or scheduled sequence.
    /// </summary>
    /// <param name="handler">
    /// Handles the external bus actions required to execute the instruction.
    /// </param>
    /// <returns>
    /// The number of T-states executed.
    /// </returns>
    public int ExecuteInstruction<THandler>(ref THandler handler)
        where THandler : IM6502BusHandler, allows ref struct
    {
        ushort scheduledSequenceStep = nextSequenceStep;
        if (scheduledSequenceStep != NoNextSequenceStep)
        {
            nextSequenceStep = NoNextSequenceStep;
            return ExecuteDecodedInstruction(scheduledSequenceStep, ref handler);
        }

        return ExecuteDecodedInstruction(OpcodeReadStep0, ref handler);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private int ExecuteDecodedInstruction<THandler>(ushort decodedStep, ref THandler handler)
        where THandler : IM6502BusHandler, allows ref struct
    {
        var instruction = Dispatch<THandler>.Instructions[decodedStep];
        return instruction(this, ref handler);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private int CompleteInstruction(bool instructionUpdatesFlags, int tStates)
    {
        var emulator = this;
        return tStates;
    }
}
