//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;

namespace MrKWatkins.OakCpu.M6502;
/// <inheritdoc/>
public sealed class M6502StepFlags : M6502Flags
{
    private readonly M6502StepEmulator emulator;

    internal M6502StepFlags(M6502StepEmulator emulator)
    {
        this.emulator = emulator;
    }

    /// <inheritdoc/>
    public override bool C
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => (emulator.P & 0b00000001) != 0; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.P = (byte)(value ? emulator.P | 0b00000001 : emulator.P & 0b11111110);
    }

    /// <inheritdoc/>
    public override bool Z
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => (emulator.P & 0b00000010) != 0; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.P = (byte)(value ? emulator.P | 0b00000010 : emulator.P & 0b11111101);
    }

    /// <inheritdoc/>
    public override bool I
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => (emulator.P & 0b00000100) != 0; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.P = (byte)(value ? emulator.P | 0b00000100 : emulator.P & 0b11111011);
    }

    /// <inheritdoc/>
    public override bool D
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => (emulator.P & 0b00001000) != 0; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.P = (byte)(value ? emulator.P | 0b00001000 : emulator.P & 0b11110111);
    }

    /// <inheritdoc/>
    public override bool B
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => (emulator.P & 0b00010000) != 0; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.P = (byte)(value ? emulator.P | 0b00010000 : emulator.P & 0b11101111);
    }

    /// <inheritdoc/>
    public override bool V
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => (emulator.P & 0b01000000) != 0; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.P = (byte)(value ? emulator.P | 0b01000000 : emulator.P & 0b10111111);
    }

    /// <inheritdoc/>
    public override bool N
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => (emulator.P & 0b10000000) != 0; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.P = (byte)(value ? emulator.P | 0b10000000 : emulator.P & 0b01111111);
    }
}
