//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.IO;

namespace MrKWatkins.OakCpu.M6502;

public sealed unsafe partial class M6502InstructionEmulator
{
    /// <summary>
    /// The number of bytes required to serialize the emulator state.
    /// </summary>
    public const int SerializedSize = 22;

    /// <summary>
    /// Serializes this emulator's M6502 CPU state.
    /// </summary>
    /// <param name="destination">
    /// The destination span to write the CPU state to.
    /// </param>
    public void Serialize(Span<byte> destination)
    {
        if (destination.Length < SerializedSize)
        {
            throw new ArgumentException("The destination span is too small.", nameof(destination));
        }

        if (opcodeStepTable == OpcodeStepTableNoPrefix)
        {
            destination[0] = (byte)0;
        }
        else
        {
            throw new InvalidOperationException("Unknown opcode step table.");
        }

        fixed (byte* block0 = &PCL)
        {
            new ReadOnlySpan<byte>((byte*)block0, 21).CopyTo(destination.Slice(1, 21));
        }
    }

    /// <summary>
    /// Serializes this emulator's M6502 CPU state.
    /// </summary>
    /// <param name="stream">
    /// The stream to write the CPU state to.
    /// </param>
    public void Serialize(Stream stream)
    {
        Span<byte> buffer = stackalloc byte[SerializedSize];
        Serialize(buffer);
        stream.Write(buffer);
    }

    /// <summary>
    /// Deserializes a M6502 CPU state.
    /// </summary>
    /// <param name="source">
    /// The serialized CPU state to read from.
    /// </param>
    /// <returns>
    /// The deserialized M6502 emulator.
    /// </returns>
    public static M6502InstructionEmulator Deserialize(ReadOnlySpan<byte> source)
    {
        var deserialized = new M6502InstructionEmulator();
        deserialized.Restore(source);
        return deserialized;
    }

    /// <summary>
    /// Deserializes a M6502 CPU state.
    /// </summary>
    /// <param name="stream">
    /// The stream to read the CPU state from.
    /// </param>
    /// <returns>
    /// The deserialized M6502 emulator.
    /// </returns>
    public static M6502InstructionEmulator Deserialize(Stream stream)
    {
        Span<byte> buffer = stackalloc byte[SerializedSize];
        stream.ReadExactly(buffer);
        return Deserialize(buffer);
    }

    /// <summary>
    /// Restores this emulator from a serialized M6502 CPU state.
    /// </summary>
    /// <param name="source">
    /// The serialized CPU state to read from.
    /// </param>
    public void Restore(ReadOnlySpan<byte> source)
    {
        if (source.Length < SerializedSize)
        {
            throw new ArgumentException("The source span is too small.", nameof(source));
        }

        opcodeStepTable = source[0] switch
        {
            0 => OpcodeStepTableNoPrefix,
            _ => throw new InvalidOperationException("Unknown opcode step table.")
        };
        fixed (byte* block0 = &PCL)
        {
            source.Slice(1, 21).CopyTo(new Span<byte>((byte*)block0, 21));
        }
    }

    /// <summary>
    /// Restores this emulator from a serialized M6502 CPU state.
    /// </summary>
    /// <param name="stream">
    /// The stream to read the CPU state from.
    /// </param>
    public void Restore(Stream stream)
    {
        Span<byte> buffer = stackalloc byte[SerializedSize];
        stream.ReadExactly(buffer);
        Restore(buffer);
    }
}
