//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;

namespace MrKWatkins.OakCpu.M6502;

public sealed unsafe partial class M6502InstructionEmulator
{
    private static readonly delegate*<M6502InstructionEmulator, Action<ActionRequired, ushort, byte>, int>[] Instructions;

    private static readonly ushort[] OpcodeStepTableNoPrefix;

    private static readonly ushort[] InterruptModeStepTable;

    static M6502InstructionEmulator()
    {
        if (!BitConverter.IsLittleEndian)
        {
#pragma warning disable CA1065
            throw new NotSupportedException("Only little endian systems are supported.");
#pragma warning restore CA1065
        }

        Instructions = 
        [
            &Opcode_read, &ora_finish, &and_finish, &eor_finish, &ldx_finish, 
            &lda_finish, &ldy_finish, &cmp_finish, &adc_finish, &sbc_finish, 
            &Halt_cycle, &Interrupt_Mode_0, &ORA_zp_X, &ORA_zp, &ASL_zp, 
            &PHP, &ORA_n, &ASL_A, &ORA_abs, &ASL_abs, 
            &ORA_zp_Y, &ORA_zp_X_15, &ASL_zp_X, &CLC, &ORA_abs_Y, 
            &ORA_abs_X, &ASL_abs_X, &AND_zp_X, &BIT_zp, &AND_zp, 
            &ROL_zp, &PLP, &AND_n, &ROL_A, &BIT_abs, 
            &AND_abs, &ROL_abs, &AND_zp_Y, &AND_zp_X_35, &ROL_zp_X, 
            &SEC, &AND_abs_Y, &AND_abs_X, &ROL_abs_X, &EOR_zp_X, 
            &EOR_zp, &LSR_zp, &PHA, &EOR_n, &LSR_A, 
            &EOR_abs, &LSR_abs, &EOR_zp_Y, &EOR_zp_X_55, &LSR_zp_X, 
            &CLI, &EOR_abs_Y, &EOR_abs_X, &LSR_abs_X, &ADC_zp_X, 
            &ADC_zp, &ROR_zp, &PLA, &ADC_n, &ROR_A, 
            &ADC_abs, &ROR_abs, &ADC_zp_Y, &ADC_zp_X_75, &ROR_zp_X, 
            &SEI, &ADC_abs_Y, &ADC_abs_X, &ROR_abs_X, &STA_zp_X, 
            &STY_zp, &STA_zp, &STX_zp, &DEY, &TXA, 
            &STY_abs, &STA_abs, &STX_abs, &STA_zp_Y, &STY_zp_X, 
            &STA_zp_X_95, &STX_zp_Y, &TYA, &STA_abs_Y, &TXS, 
            &STA_abs_X, &LDY_n, &LDA_zp_X, &LDX_n, &LDY_zp, 
            &LDA_zp, &LDX_zp, &TAY, &LDA_n, &TAX, 
            &LDY_abs, &LDA_abs, &LDX_abs, &LDA_zp_Y, &LDY_zp_X, 
            &LDA_zp_X_B5, &LDX_zp_Y, &CLV, &LDA_abs_Y, &TSX, 
            &LDY_abs_X, &LDA_abs_X, &LDX_abs_Y, &CPY_n, &CMP_zp_X, 
            &CPY_zp, &CMP_zp, &DEC_zp, &INY, &CMP_n, 
            &DEX, &CPY_abs, &CMP_abs, &DEC_abs, &CMP_zp_Y, 
            &CMP_zp_X_D5, &DEC_zp_X, &CLD, &CMP_abs_Y, &CMP_abs_X, 
            &DEC_abs_X, &CPX_n, &SBC_zp_X, &CPX_zp, &SBC_zp, 
            &INC_zp, &INX, &SBC_n, &NOP, &CPX_abs, 
            &SBC_abs, &INC_abs, &SBC_zp_Y, &SBC_zp_X_F5, &INC_zp_X, 
            &SED, &SBC_abs_Y, &SBC_abs_X, &INC_abs_X, &Error
        ];
        OpcodeStepTableNoPrefix = 
        [
            149, 12, 149, 149, 149, 13, 14, 149, 15, 16, 
            17, 149, 149, 18, 19, 149, 149, 20, 149, 149, 
            149, 21, 22, 149, 23, 24, 149, 149, 149, 25, 
            26, 149, 149, 27, 149, 149, 28, 29, 30, 149, 
            31, 32, 33, 149, 34, 35, 36, 149, 149, 37, 
            149, 149, 149, 38, 39, 149, 40, 41, 149, 149, 
            149, 42, 43, 149, 149, 44, 149, 149, 149, 45, 
            46, 149, 47, 48, 49, 149, 149, 50, 51, 149, 
            149, 52, 149, 149, 149, 53, 54, 149, 55, 56, 
            149, 149, 149, 57, 58, 149, 149, 59, 149, 149, 
            149, 60, 61, 149, 62, 63, 64, 149, 149, 65, 
            66, 149, 149, 67, 149, 149, 149, 68, 69, 149, 
            70, 71, 149, 149, 149, 72, 73, 149, 149, 74, 
            149, 149, 75, 76, 77, 149, 78, 149, 79, 149, 
            80, 81, 82, 149, 149, 83, 149, 149, 84, 85, 
            86, 149, 87, 88, 89, 149, 149, 90, 149, 149, 
            91, 92, 93, 149, 94, 95, 96, 149, 97, 98, 
            99, 149, 100, 101, 102, 149, 149, 103, 149, 149, 
            104, 105, 106, 149, 107, 108, 109, 149, 110, 111, 
            112, 149, 113, 114, 149, 149, 115, 116, 117, 149, 
            118, 119, 120, 149, 121, 122, 123, 149, 149, 124, 
            149, 149, 149, 125, 126, 149, 127, 128, 149, 149, 
            149, 129, 130, 149, 131, 132, 149, 149, 133, 134, 
            135, 149, 136, 137, 138, 149, 139, 140, 141, 149, 
            149, 142, 149, 149, 149, 143, 144, 149, 145, 146, 
            149, 149, 149, 147, 148, 149
        ];
        InterruptModeStepTable = [11];
    }
}
