//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;

namespace MrKWatkins.OakCpu.M6502;

public sealed unsafe partial class M6502StepEmulator
{
    private const ushort OpcodeReadStep0 = 0;

    private const ushort HaltedStep0 = 11;

    private const ushort IM0Step0 = 13;

    private static readonly Step[] Steps;

    private static readonly delegate*<M6502StepEmulator, void>[] Overlaps;

    private static readonly ushort[] OpcodeStepTableNoPrefix;

    private static readonly ushort[] InterruptModeStepTable;

    static M6502StepEmulator()
    {
        if (!BitConverter.IsLittleEndian)
        {
#pragma warning disable CA1065
            throw new NotSupportedException("Only little endian systems are supported.");
#pragma warning restore CA1065
        }

        Steps = 
        [
            new(&Step0, 1, ActionRequired.OpcodeRead, default), new(&Step1, 532, ActionRequired.None, default), new(&Step2, 532, ActionRequired.None, default), new(&Step3, 532, ActionRequired.None, default), new(&Step4, 532, ActionRequired.None, default), 
            new(&Step5, 532, ActionRequired.None, default), new(&Step6, 532, ActionRequired.None, default), new(&Step7, 532, ActionRequired.None, default), new(&Step8, 532, ActionRequired.None, default), new(&Step9, 532, ActionRequired.None, default), 
            new(&Step10, 532, ActionRequired.None, default), new(&Step0, 12, ActionRequired.OpcodeRead, default), new(&Step11, 11, ActionRequired.None, default), new(default, 0, ActionRequired.None, default), new(&Step12, 15, ActionRequired.MemoryRead, default), 
            new(&Step13, 16, ActionRequired.MemoryRead, default), new(&Step14, 17, ActionRequired.MemoryRead, default), new(&Step15, 18, ActionRequired.MemoryRead, default), new(&Step16, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap0), 
            new(&Step12, 21, ActionRequired.MemoryRead, default), new(&Step18, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap0), new(&Step19, 24, ActionRequired.MemoryRead, default), new(&Step20, 25, ActionRequired.MemoryRead, default), 
            new(&Step21, 26, ActionRequired.MemoryWrite, default), new(&Step22, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Step24, 29, ActionRequired.MemoryRead, default), new(&Step25, 0, ActionRequired.MemoryWrite, default), 
            new(default, 0, ActionRequired.None, &Overlap1), new(&Step26, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap0), new(default, 0, ActionRequired.None, &Overlap2), new(&Step12, 35, ActionRequired.MemoryRead, default), 
            new(&Step28, 36, ActionRequired.MemoryRead, default), new(&Step16, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap0), new(&Step19, 39, ActionRequired.MemoryRead, default), new(&Step29, 40, ActionRequired.MemoryRead, default), 
            new(&Step30, 41, ActionRequired.MemoryRead, default), new(&Step21, 42, ActionRequired.MemoryWrite, default), new(&Step22, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Step19, 45, ActionRequired.MemoryRead, default), 
            new(&Step31, 46, ActionRequired.MemoryRead, default), new(&Step32, 47, ActionRequired.MemoryRead, default), new(&Step33, 48, ActionRequired.MemoryRead, default), new(&Step34, 532, ActionRequired.MemoryRead, default), new(&Step12, 50, ActionRequired.MemoryRead, default), 
            new(&Step13, 51, ActionRequired.MemoryRead, default), new(&Step35, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap0), new(&Step19, 54, ActionRequired.MemoryRead, default), new(&Step31, 55, ActionRequired.MemoryRead, default), 
            new(&Step36, 56, ActionRequired.MemoryRead, default), new(&Step21, 57, ActionRequired.MemoryWrite, default), new(&Step22, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(default, 0, ActionRequired.None, &Overlap3), 
            new(&Step19, 61, ActionRequired.MemoryRead, default), new(&Step29, 62, ActionRequired.MemoryRead, default), new(&Step38, 63, ActionRequired.MemoryRead, default), new(&Step34, 532, ActionRequired.MemoryRead, default), new(&Step19, 65, ActionRequired.MemoryRead, default), 
            new(&Step29, 66, ActionRequired.MemoryRead, default), new(&Step39, 67, ActionRequired.MemoryRead, default), new(&Step40, 532, ActionRequired.MemoryRead, default), new(&Step19, 69, ActionRequired.MemoryRead, default), new(&Step29, 70, ActionRequired.MemoryRead, default), 
            new(&Step41, 71, ActionRequired.MemoryRead, default), new(&Step42, 72, ActionRequired.MemoryRead, default), new(&Step21, 73, ActionRequired.MemoryWrite, default), new(&Step22, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), 
            new(&Step12, 76, ActionRequired.MemoryRead, default), new(&Step13, 77, ActionRequired.MemoryRead, default), new(&Step14, 78, ActionRequired.MemoryRead, default), new(&Step15, 79, ActionRequired.MemoryRead, default), new(&Step43, 0, ActionRequired.MemoryRead, default), 
            new(default, 0, ActionRequired.None, &Overlap4), new(&Step12, 82, ActionRequired.MemoryRead, default), new(&Step45, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap5), new(&Step12, 85, ActionRequired.MemoryRead, default), 
            new(&Step47, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap4), new(&Step19, 88, ActionRequired.MemoryRead, default), new(&Step20, 89, ActionRequired.MemoryRead, default), new(&Step21, 90, ActionRequired.MemoryWrite, default), 
            new(&Step48, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Step24, 93, ActionRequired.MemoryRead, default), new(&Step49, 94, ActionRequired.MemoryRead, default), new(&Step50, 0, ActionRequired.MemoryRead, default), 
            new(default, 0, ActionRequired.None, &Overlap6), new(&Step52, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap4), new(default, 0, ActionRequired.None, &Overlap7), new(&Step12, 100, ActionRequired.MemoryRead, default), 
            new(&Step28, 101, ActionRequired.MemoryRead, default), new(&Step54, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap5), new(&Step12, 104, ActionRequired.MemoryRead, default), new(&Step28, 105, ActionRequired.MemoryRead, default), 
            new(&Step43, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap4), new(&Step19, 108, ActionRequired.MemoryRead, default), new(&Step29, 109, ActionRequired.MemoryRead, default), new(&Step30, 110, ActionRequired.MemoryRead, default), 
            new(&Step21, 111, ActionRequired.MemoryWrite, default), new(&Step48, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Step19, 114, ActionRequired.MemoryRead, default), new(&Step31, 115, ActionRequired.MemoryRead, default), 
            new(&Step32, 116, ActionRequired.MemoryRead, default), new(&Step55, 117, ActionRequired.MemoryRead, default), new(&Step56, 532, ActionRequired.MemoryRead, default), new(&Step12, 119, ActionRequired.MemoryRead, default), new(&Step13, 120, ActionRequired.MemoryRead, default), 
            new(&Step57, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap4), new(&Step19, 123, ActionRequired.MemoryRead, default), new(&Step31, 124, ActionRequired.MemoryRead, default), new(&Step36, 125, ActionRequired.MemoryRead, default), 
            new(&Step21, 126, ActionRequired.MemoryWrite, default), new(&Step48, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(default, 0, ActionRequired.None, &Overlap8), new(&Step19, 130, ActionRequired.MemoryRead, default), 
            new(&Step29, 131, ActionRequired.MemoryRead, default), new(&Step59, 132, ActionRequired.MemoryRead, default), new(&Step56, 532, ActionRequired.MemoryRead, default), new(&Step19, 134, ActionRequired.MemoryRead, default), new(&Step29, 135, ActionRequired.MemoryRead, default), 
            new(&Step60, 136, ActionRequired.MemoryRead, default), new(&Step61, 532, ActionRequired.MemoryRead, default), new(&Step19, 138, ActionRequired.MemoryRead, default), new(&Step29, 139, ActionRequired.MemoryRead, default), new(&Step41, 140, ActionRequired.MemoryRead, default), 
            new(&Step42, 141, ActionRequired.MemoryRead, default), new(&Step21, 142, ActionRequired.MemoryWrite, default), new(&Step48, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Step12, 145, ActionRequired.MemoryRead, default), 
            new(&Step13, 146, ActionRequired.MemoryRead, default), new(&Step14, 147, ActionRequired.MemoryRead, default), new(&Step15, 148, ActionRequired.MemoryRead, default), new(&Step62, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap9), 
            new(&Step12, 151, ActionRequired.MemoryRead, default), new(&Step64, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap9), new(&Step19, 154, ActionRequired.MemoryRead, default), new(&Step20, 155, ActionRequired.MemoryRead, default), 
            new(&Step21, 156, ActionRequired.MemoryWrite, default), new(&Step65, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Step24, 159, ActionRequired.MemoryRead, default), new(&Step66, 0, ActionRequired.MemoryWrite, default), 
            new(default, 0, ActionRequired.None, &Overlap1), new(&Step67, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap9), new(default, 0, ActionRequired.None, &Overlap10), new(&Step12, 165, ActionRequired.MemoryRead, default), 
            new(&Step28, 166, ActionRequired.MemoryRead, default), new(&Step62, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap9), new(&Step19, 169, ActionRequired.MemoryRead, default), new(&Step29, 170, ActionRequired.MemoryRead, default), 
            new(&Step30, 171, ActionRequired.MemoryRead, default), new(&Step21, 172, ActionRequired.MemoryWrite, default), new(&Step65, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Step19, 175, ActionRequired.MemoryRead, default), 
            new(&Step31, 176, ActionRequired.MemoryRead, default), new(&Step32, 177, ActionRequired.MemoryRead, default), new(&Step69, 178, ActionRequired.MemoryRead, default), new(&Step70, 532, ActionRequired.MemoryRead, default), new(&Step12, 180, ActionRequired.MemoryRead, default), 
            new(&Step13, 181, ActionRequired.MemoryRead, default), new(&Step71, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap9), new(&Step19, 184, ActionRequired.MemoryRead, default), new(&Step31, 185, ActionRequired.MemoryRead, default), 
            new(&Step36, 186, ActionRequired.MemoryRead, default), new(&Step21, 187, ActionRequired.MemoryWrite, default), new(&Step65, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(default, 0, ActionRequired.None, &Overlap11), 
            new(&Step19, 191, ActionRequired.MemoryRead, default), new(&Step29, 192, ActionRequired.MemoryRead, default), new(&Step73, 193, ActionRequired.MemoryRead, default), new(&Step70, 532, ActionRequired.MemoryRead, default), new(&Step19, 195, ActionRequired.MemoryRead, default), 
            new(&Step29, 196, ActionRequired.MemoryRead, default), new(&Step74, 197, ActionRequired.MemoryRead, default), new(&Step75, 532, ActionRequired.MemoryRead, default), new(&Step19, 199, ActionRequired.MemoryRead, default), new(&Step29, 200, ActionRequired.MemoryRead, default), 
            new(&Step41, 201, ActionRequired.MemoryRead, default), new(&Step42, 202, ActionRequired.MemoryRead, default), new(&Step21, 203, ActionRequired.MemoryWrite, default), new(&Step65, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), 
            new(&Step19, 206, ActionRequired.MemoryRead, default), new(&Step31, 207, ActionRequired.MemoryRead, default), new(&Step76, 208, ActionRequired.MemoryRead, default), new(&Step32, 209, ActionRequired.MemoryRead, default), new(&Step77, 0, ActionRequired.MemoryRead, default), 
            new(default, 0, ActionRequired.None, &Overlap12), new(&Step19, 212, ActionRequired.MemoryRead, default), new(&Step79, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap12), new(&Step19, 215, ActionRequired.MemoryRead, default), 
            new(&Step20, 216, ActionRequired.MemoryRead, default), new(&Step21, 217, ActionRequired.MemoryWrite, default), new(&Step80, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Step81, 220, ActionRequired.MemoryRead, default), 
            new(&Step82, 221, ActionRequired.MemoryRead, default), new(&Step83, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap13), new(&Step85, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap12), 
            new(default, 0, ActionRequired.None, &Overlap14), new(&Step19, 227, ActionRequired.MemoryRead, default), new(&Step29, 228, ActionRequired.MemoryRead, default), new(&Step77, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap12), 
            new(&Step19, 231, ActionRequired.MemoryRead, default), new(&Step29, 232, ActionRequired.MemoryRead, default), new(&Step30, 233, ActionRequired.MemoryRead, default), new(&Step21, 234, ActionRequired.MemoryWrite, default), new(&Step80, 0, ActionRequired.MemoryWrite, default), 
            new(default, 0, ActionRequired.None, &Overlap1), new(&Step19, 237, ActionRequired.MemoryRead, default), new(&Step31, 238, ActionRequired.MemoryRead, default), new(&Step32, 239, ActionRequired.MemoryRead, default), new(&Step87, 240, ActionRequired.MemoryRead, default), 
            new(&Step88, 532, ActionRequired.MemoryRead, default), new(&Step19, 242, ActionRequired.MemoryRead, default), new(&Step31, 243, ActionRequired.MemoryRead, default), new(&Step89, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap12), 
            new(&Step19, 246, ActionRequired.MemoryRead, default), new(&Step31, 247, ActionRequired.MemoryRead, default), new(&Step36, 248, ActionRequired.MemoryRead, default), new(&Step21, 249, ActionRequired.MemoryWrite, default), new(&Step80, 0, ActionRequired.MemoryWrite, default), 
            new(default, 0, ActionRequired.None, &Overlap1), new(default, 0, ActionRequired.None, &Overlap15), new(&Step19, 253, ActionRequired.MemoryRead, default), new(&Step29, 254, ActionRequired.MemoryRead, default), new(&Step91, 255, ActionRequired.MemoryRead, default), 
            new(&Step88, 532, ActionRequired.MemoryRead, default), new(&Step19, 257, ActionRequired.MemoryRead, default), new(&Step29, 258, ActionRequired.MemoryRead, default), new(&Step92, 259, ActionRequired.MemoryRead, default), new(&Step93, 532, ActionRequired.MemoryRead, default), 
            new(&Step19, 261, ActionRequired.MemoryRead, default), new(&Step29, 262, ActionRequired.MemoryRead, default), new(&Step41, 263, ActionRequired.MemoryRead, default), new(&Step42, 264, ActionRequired.MemoryRead, default), new(&Step21, 265, ActionRequired.MemoryWrite, default), 
            new(&Step80, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Step19, 268, ActionRequired.MemoryRead, default), new(&Step31, 269, ActionRequired.MemoryRead, default), new(&Step76, 270, ActionRequired.MemoryRead, default), 
            new(&Step32, 271, ActionRequired.MemoryRead, default), new(&Step94, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Step19, 274, ActionRequired.MemoryRead, default), new(&Step95, 0, ActionRequired.MemoryWrite, default), 
            new(default, 0, ActionRequired.None, &Overlap1), new(&Step19, 277, ActionRequired.MemoryRead, default), new(&Step96, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Step19, 280, ActionRequired.MemoryRead, default), 
            new(&Step97, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(default, 0, ActionRequired.None, &Overlap16), new(default, 0, ActionRequired.None, &Overlap17), new(&Step19, 285, ActionRequired.MemoryRead, default), 
            new(&Step29, 286, ActionRequired.MemoryRead, default), new(&Step100, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Step19, 289, ActionRequired.MemoryRead, default), new(&Step29, 290, ActionRequired.MemoryRead, default), 
            new(&Step94, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Step19, 293, ActionRequired.MemoryRead, default), new(&Step29, 294, ActionRequired.MemoryRead, default), new(&Step101, 0, ActionRequired.MemoryWrite, default), 
            new(default, 0, ActionRequired.None, &Overlap1), new(&Step19, 297, ActionRequired.MemoryRead, default), new(&Step31, 298, ActionRequired.MemoryRead, default), new(&Step32, 299, ActionRequired.MemoryRead, default), new(&Step102, 300, ActionRequired.MemoryRead, default), 
            new(&Step103, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Step19, 303, ActionRequired.MemoryRead, default), new(&Step31, 304, ActionRequired.MemoryRead, default), new(&Step104, 0, ActionRequired.MemoryWrite, default), 
            new(default, 0, ActionRequired.None, &Overlap1), new(&Step19, 307, ActionRequired.MemoryRead, default), new(&Step31, 308, ActionRequired.MemoryRead, default), new(&Step105, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), 
            new(&Step19, 311, ActionRequired.MemoryRead, default), new(&Step31, 312, ActionRequired.MemoryRead, default), new(&Step106, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(default, 0, ActionRequired.None, &Overlap18), 
            new(&Step19, 316, ActionRequired.MemoryRead, default), new(&Step29, 317, ActionRequired.MemoryRead, default), new(&Step108, 318, ActionRequired.MemoryRead, default), new(&Step103, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), 
            new(default, 0, ActionRequired.None, &Overlap19), new(&Step19, 322, ActionRequired.MemoryRead, default), new(&Step29, 323, ActionRequired.MemoryRead, default), new(&Step41, 324, ActionRequired.MemoryRead, default), new(&Step110, 0, ActionRequired.MemoryWrite, default), 
            new(default, 0, ActionRequired.None, &Overlap1), new(&Step111, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap20), new(&Step12, 329, ActionRequired.MemoryRead, default), new(&Step13, 330, ActionRequired.MemoryRead, default), 
            new(&Step14, 331, ActionRequired.MemoryRead, default), new(&Step15, 332, ActionRequired.MemoryRead, default), new(&Step113, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap13), new(&Step114, 0, ActionRequired.MemoryRead, default), 
            new(default, 0, ActionRequired.None, &Overlap21), new(&Step12, 337, ActionRequired.MemoryRead, default), new(&Step116, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap20), new(&Step12, 340, ActionRequired.MemoryRead, default), 
            new(&Step117, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap13), new(&Step12, 343, ActionRequired.MemoryRead, default), new(&Step118, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap21), 
            new(default, 0, ActionRequired.None, &Overlap22), new(&Step120, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap13), new(default, 0, ActionRequired.None, &Overlap23), new(&Step12, 350, ActionRequired.MemoryRead, default), 
            new(&Step28, 351, ActionRequired.MemoryRead, default), new(&Step122, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap20), new(&Step12, 354, ActionRequired.MemoryRead, default), new(&Step28, 355, ActionRequired.MemoryRead, default), 
            new(&Step113, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap13), new(&Step12, 358, ActionRequired.MemoryRead, default), new(&Step28, 359, ActionRequired.MemoryRead, default), new(&Step123, 0, ActionRequired.MemoryRead, default), 
            new(default, 0, ActionRequired.None, &Overlap21), new(&Step19, 362, ActionRequired.MemoryRead, default), new(&Step31, 363, ActionRequired.MemoryRead, default), new(&Step32, 364, ActionRequired.MemoryRead, default), new(&Step124, 365, ActionRequired.MemoryRead, default), 
            new(&Step125, 532, ActionRequired.MemoryRead, default), new(&Step12, 367, ActionRequired.MemoryRead, default), new(&Step13, 368, ActionRequired.MemoryRead, default), new(&Step126, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap20), 
            new(&Step12, 371, ActionRequired.MemoryRead, default), new(&Step13, 372, ActionRequired.MemoryRead, default), new(&Step127, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap13), new(&Step12, 375, ActionRequired.MemoryRead, default), 
            new(&Step13, 376, ActionRequired.MemoryRead, default), new(&Step128, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap21), new(default, 0, ActionRequired.None, &Overlap24), new(&Step19, 380, ActionRequired.MemoryRead, default), 
            new(&Step29, 381, ActionRequired.MemoryRead, default), new(&Step130, 382, ActionRequired.MemoryRead, default), new(&Step125, 532, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap25), new(&Step19, 385, ActionRequired.MemoryRead, default), 
            new(&Step29, 386, ActionRequired.MemoryRead, default), new(&Step132, 387, ActionRequired.MemoryRead, default), new(&Step133, 532, ActionRequired.MemoryRead, default), new(&Step19, 389, ActionRequired.MemoryRead, default), new(&Step29, 390, ActionRequired.MemoryRead, default), 
            new(&Step134, 391, ActionRequired.MemoryRead, default), new(&Step135, 532, ActionRequired.MemoryRead, default), new(&Step19, 393, ActionRequired.MemoryRead, default), new(&Step29, 394, ActionRequired.MemoryRead, default), new(&Step136, 395, ActionRequired.MemoryRead, default), 
            new(&Step137, 532, ActionRequired.MemoryRead, default), new(&Step138, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap26), new(&Step12, 399, ActionRequired.MemoryRead, default), new(&Step13, 400, ActionRequired.MemoryRead, default), 
            new(&Step14, 401, ActionRequired.MemoryRead, default), new(&Step15, 402, ActionRequired.MemoryRead, default), new(&Step140, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap27), new(&Step12, 405, ActionRequired.MemoryRead, default), 
            new(&Step142, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap26), new(&Step12, 408, ActionRequired.MemoryRead, default), new(&Step143, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap27), 
            new(&Step19, 411, ActionRequired.MemoryRead, default), new(&Step20, 412, ActionRequired.MemoryRead, default), new(&Step21, 413, ActionRequired.MemoryWrite, default), new(&Step144, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), 
            new(default, 0, ActionRequired.None, &Overlap28), new(&Step146, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap27), new(default, 0, ActionRequired.None, &Overlap29), new(&Step12, 420, ActionRequired.MemoryRead, default), 
            new(&Step28, 421, ActionRequired.MemoryRead, default), new(&Step148, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap26), new(&Step12, 424, ActionRequired.MemoryRead, default), new(&Step28, 425, ActionRequired.MemoryRead, default), 
            new(&Step140, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap27), new(&Step19, 428, ActionRequired.MemoryRead, default), new(&Step29, 429, ActionRequired.MemoryRead, default), new(&Step30, 430, ActionRequired.MemoryRead, default), 
            new(&Step21, 431, ActionRequired.MemoryWrite, default), new(&Step144, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Step19, 434, ActionRequired.MemoryRead, default), new(&Step31, 435, ActionRequired.MemoryRead, default), 
            new(&Step32, 436, ActionRequired.MemoryRead, default), new(&Step149, 437, ActionRequired.MemoryRead, default), new(&Step150, 532, ActionRequired.MemoryRead, default), new(&Step12, 439, ActionRequired.MemoryRead, default), new(&Step13, 440, ActionRequired.MemoryRead, default), 
            new(&Step151, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap27), new(&Step19, 443, ActionRequired.MemoryRead, default), new(&Step31, 444, ActionRequired.MemoryRead, default), new(&Step36, 445, ActionRequired.MemoryRead, default), 
            new(&Step21, 446, ActionRequired.MemoryWrite, default), new(&Step144, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(default, 0, ActionRequired.None, &Overlap30), new(&Step19, 450, ActionRequired.MemoryRead, default), 
            new(&Step29, 451, ActionRequired.MemoryRead, default), new(&Step153, 452, ActionRequired.MemoryRead, default), new(&Step150, 532, ActionRequired.MemoryRead, default), new(&Step19, 454, ActionRequired.MemoryRead, default), new(&Step29, 455, ActionRequired.MemoryRead, default), 
            new(&Step154, 456, ActionRequired.MemoryRead, default), new(&Step155, 532, ActionRequired.MemoryRead, default), new(&Step19, 458, ActionRequired.MemoryRead, default), new(&Step29, 459, ActionRequired.MemoryRead, default), new(&Step41, 460, ActionRequired.MemoryRead, default), 
            new(&Step42, 461, ActionRequired.MemoryRead, default), new(&Step21, 462, ActionRequired.MemoryWrite, default), new(&Step144, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Step156, 0, ActionRequired.MemoryRead, default), 
            new(default, 0, ActionRequired.None, &Overlap31), new(&Step19, 467, ActionRequired.MemoryRead, default), new(&Step31, 468, ActionRequired.MemoryRead, default), new(&Step76, 469, ActionRequired.MemoryRead, default), new(&Step32, 470, ActionRequired.MemoryRead, default), 
            new(&Step158, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap32), new(&Step12, 473, ActionRequired.MemoryRead, default), new(&Step160, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap31), 
            new(&Step19, 476, ActionRequired.MemoryRead, default), new(&Step161, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap32), new(&Step19, 479, ActionRequired.MemoryRead, default), new(&Step20, 480, ActionRequired.MemoryRead, default), 
            new(&Step21, 481, ActionRequired.MemoryWrite, default), new(&Step162, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(default, 0, ActionRequired.None, &Overlap33), new(&Step164, 0, ActionRequired.MemoryRead, default), 
            new(default, 0, ActionRequired.None, &Overlap32), new(default, 0, ActionRequired.None, &Overlap1), new(&Step12, 488, ActionRequired.MemoryRead, default), new(&Step28, 489, ActionRequired.MemoryRead, default), new(&Step165, 0, ActionRequired.MemoryRead, default), 
            new(default, 0, ActionRequired.None, &Overlap31), new(&Step19, 492, ActionRequired.MemoryRead, default), new(&Step29, 493, ActionRequired.MemoryRead, default), new(&Step158, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap32), 
            new(&Step19, 496, ActionRequired.MemoryRead, default), new(&Step29, 497, ActionRequired.MemoryRead, default), new(&Step30, 498, ActionRequired.MemoryRead, default), new(&Step21, 499, ActionRequired.MemoryWrite, default), new(&Step162, 0, ActionRequired.MemoryWrite, default), 
            new(default, 0, ActionRequired.None, &Overlap1), new(&Step19, 502, ActionRequired.MemoryRead, default), new(&Step31, 503, ActionRequired.MemoryRead, default), new(&Step32, 504, ActionRequired.MemoryRead, default), new(&Step166, 505, ActionRequired.MemoryRead, default), 
            new(&Step167, 532, ActionRequired.MemoryRead, default), new(&Step19, 507, ActionRequired.MemoryRead, default), new(&Step31, 508, ActionRequired.MemoryRead, default), new(&Step168, 0, ActionRequired.MemoryRead, default), new(default, 0, ActionRequired.None, &Overlap32), 
            new(&Step19, 511, ActionRequired.MemoryRead, default), new(&Step31, 512, ActionRequired.MemoryRead, default), new(&Step36, 513, ActionRequired.MemoryRead, default), new(&Step21, 514, ActionRequired.MemoryWrite, default), new(&Step162, 0, ActionRequired.MemoryWrite, default), 
            new(default, 0, ActionRequired.None, &Overlap1), new(default, 0, ActionRequired.None, &Overlap34), new(&Step19, 518, ActionRequired.MemoryRead, default), new(&Step29, 519, ActionRequired.MemoryRead, default), new(&Step170, 520, ActionRequired.MemoryRead, default), 
            new(&Step167, 532, ActionRequired.MemoryRead, default), new(&Step19, 522, ActionRequired.MemoryRead, default), new(&Step29, 523, ActionRequired.MemoryRead, default), new(&Step171, 524, ActionRequired.MemoryRead, default), new(&Step172, 532, ActionRequired.MemoryRead, default), 
            new(&Step19, 526, ActionRequired.MemoryRead, default), new(&Step29, 527, ActionRequired.MemoryRead, default), new(&Step41, 528, ActionRequired.MemoryRead, default), new(&Step42, 529, ActionRequired.MemoryRead, default), new(&Step21, 530, ActionRequired.MemoryWrite, default), 
            new(&Step162, 0, ActionRequired.MemoryWrite, default), new(default, 0, ActionRequired.None, &Overlap1), new(&Error, 0, ActionRequired.None, default)
        ];
        Overlaps = 
        [
            default(delegate*<M6502StepEmulator, void>), &Overlap0, &Overlap1, &Overlap2, &Overlap3, 
            &Overlap4, &Overlap5, &Overlap6, &Overlap7, &Overlap8, 
            &Overlap9, &Overlap10, &Overlap11, &Overlap12, &Overlap13, 
            &Overlap14, &Overlap15, &Overlap16, &Overlap17, &Overlap18, 
            &Overlap19, &Overlap20, &Overlap21, &Overlap22, &Overlap23, 
            &Overlap24, &Overlap25, &Overlap26, &Overlap27, &Overlap28, 
            &Overlap29, &Overlap30, &Overlap31, &Overlap32, &Overlap33, 
            &Overlap34
        ];
        OpcodeStepTableNoPrefix = 
        [
            532, 14, 532, 532, 532, 20, 23, 532, 28, 31, 
            33, 532, 532, 34, 38, 532, 532, 44, 532, 532, 
            532, 49, 53, 532, 59, 60, 532, 532, 532, 64, 
            68, 532, 532, 75, 532, 532, 81, 84, 87, 532, 
            92, 96, 98, 532, 99, 103, 107, 532, 532, 113, 
            532, 532, 532, 118, 122, 532, 128, 129, 532, 532, 
            532, 133, 137, 532, 532, 144, 532, 532, 532, 150, 
            153, 532, 158, 161, 163, 532, 532, 164, 168, 532, 
            532, 174, 532, 532, 532, 179, 183, 532, 189, 190, 
            532, 532, 532, 194, 198, 532, 532, 205, 532, 532, 
            532, 211, 214, 532, 219, 223, 225, 532, 532, 226, 
            230, 532, 532, 236, 532, 532, 532, 241, 245, 532, 
            251, 252, 532, 532, 532, 256, 260, 532, 532, 267, 
            532, 532, 273, 276, 279, 532, 282, 532, 283, 532, 
            284, 288, 292, 532, 532, 296, 532, 532, 302, 306, 
            310, 532, 314, 315, 320, 532, 532, 321, 532, 532, 
            326, 328, 334, 532, 336, 339, 342, 532, 345, 346, 
            348, 532, 349, 353, 357, 532, 532, 361, 532, 532, 
            366, 370, 374, 532, 378, 379, 383, 532, 384, 388, 
            392, 532, 396, 398, 532, 532, 404, 407, 410, 532, 
            415, 416, 418, 532, 419, 423, 427, 532, 532, 433, 
            532, 532, 532, 438, 442, 532, 448, 449, 532, 532, 
            532, 453, 457, 532, 464, 466, 532, 532, 472, 475, 
            478, 532, 483, 484, 486, 532, 487, 491, 495, 532, 
            532, 501, 532, 532, 532, 506, 510, 532, 516, 517, 
            532, 532, 532, 521, 525, 532
        ];
        InterruptModeStepTable = [13];
    }
}
