//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace MrKWatkins.OakCpu.M6502;
/// <summary>
/// Provides access to the M6502 flags.
/// </summary>
public abstract class M6502Flags
{
    /// <summary>
    /// Gets or sets the carry flag.
    /// </summary>
    public abstract bool C { get; set; }

    /// <summary>
    /// Gets or sets the zero flag.
    /// </summary>
    public abstract bool Z { get; set; }

    /// <summary>
    /// Gets or sets the interrupt disable flag.
    /// </summary>
    public abstract bool I { get; set; }

    /// <summary>
    /// Gets or sets the decimal flag.
    /// </summary>
    public abstract bool D { get; set; }

    /// <summary>
    /// Gets or sets the break flag.
    /// </summary>
    public abstract bool B { get; set; }

    /// <summary>
    /// Gets or sets the overflow flag.
    /// </summary>
    public abstract bool V { get; set; }

    /// <summary>
    /// Gets or sets the negative flag.
    /// </summary>
    public abstract bool N { get; set; }
}
