//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MrKWatkins.OakCpu.M6502;
/// <summary>
/// Represents a cycle-accurate M6502 emulator that executes one T-state at a time.
/// </summary>
[StructLayout(LayoutKind.Explicit)]
public sealed unsafe partial class M6502StepEmulator
{
    [FieldOffset(0)]
    internal ushort PC;

    [FieldOffset(0)]
    internal byte PCL;

    [FieldOffset(1)]
    internal byte PCH;

    [FieldOffset(2)]
    internal byte A;

    [FieldOffset(3)]
    internal byte P;

    [FieldOffset(4)]
    internal byte S;

    [FieldOffset(5)]
    internal byte X;

    [FieldOffset(6)]
    internal byte Y;

    /// <summary>
    /// Initializes a new M6502StepEmulator instance.
    /// </summary>
    public M6502StepEmulator()
    {
        opcodeStepTable = OpcodeStepTableNoPrefix;
        Registers = new M6502StepRegisters(this);
        Flags = new M6502StepFlags(this);
        Interrupts = new M6502StepInterrupts(this);
    }

    [FieldOffset(7)]
    private ushort ad;

    [FieldOffset(9)]
    private ushort interruptvector;

    [FieldOffset(11)]
    private ushort address;

    /// <summary>
    /// Gets the address for the current external bus action.
    /// </summary>
    public ushort Address
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => address;
    }

    [FieldOffset(13)]
    private ushort currentStep;

    [FieldOffset(15)]
    private bool pendingnmi;

    [FieldOffset(16)]
    private bool previousnmi;

    [FieldOffset(17)]
    private bool sampledirq;

    [FieldOffset(18)]
    internal bool irq;

    [FieldOffset(19)]
    internal bool nmi;

    [FieldOffset(20)]
    private byte data;

    /// <summary>
    /// Gets or sets the data value for the current external bus action.
    /// </summary>
    public byte Data
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => data; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => data = value;
    }

    /// <summary>
    /// Gets the M6502 registers.
    /// </summary>
    [field: FieldOffset(24)]
    public M6502Registers Registers
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get;
    }

    /// <summary>
    /// Gets the M6502 flags.
    /// </summary>
    [field: FieldOffset(32)]
    public M6502Flags Flags
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get;
    }

    /// <summary>
    /// Gets the M6502 interrupt state.
    /// </summary>
    [field: FieldOffset(40)]
    public M6502Interrupts Interrupts
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get;
    }

    [FieldOffset(48)]
    private ushort[] opcodeStepTable;

    [FieldOffset(56)]
    private delegate*<M6502StepEmulator, void> overlapPipeline;
}
