//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MrKWatkins.OakCpu.M6502;

public sealed unsafe partial class M6502StepEmulator
{
    /// <summary>
    /// Executes one M6502 T-state.
    /// </summary>
    /// <returns>
    /// The external action that the host must perform for the completed T-state.
    /// </returns>
    public ActionRequired Step()
    {
        var step = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(Steps), currentStep);
        currentStep = step.NextStep;
        var actionRequired = step.ActionRequired;
        if (step.Handler != default)
        {
            step.Handler(this, ref actionRequired);
        }

        return actionRequired;
    }

    private static void Error(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        throw new NotSupportedException("Opcode not supported");
    }

    // Opcode read [0]
    // Halt cycle [0]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void Step0(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        // Execute queued overlap.
        emulator.ExecuteOverlap();
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
    }

    // Opcode read [1]
    private static void Step1(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.currentStep = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(emulator.opcodeStepTable), emulator.data);
        var selectedStep = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(Steps), emulator.currentStep);
        if (selectedStep.Overlap != default)
        {
            // Queue overlap step.
            emulator.overlapPipeline = selectedStep.Overlap;
            emulator.currentStep = selectedStep.NextStep;
            // Check interrupts at the instruction boundary.
            if (HandleInterrupts(emulator, ref actionRequired))
            {
                return;
            }
        }
    }

    // Halt cycle [1]
    private static void Step2(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.currentStep = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(emulator.opcodeStepTable), emulator.data);
        var selectedStep = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(Steps), emulator.currentStep);
        if (selectedStep.Overlap != default)
        {
            // Queue overlap step.
            emulator.overlapPipeline = selectedStep.Overlap;
            emulator.currentStep = selectedStep.NextStep;
            // Check interrupts at the instruction boundary.
            if (HandleInterrupts(emulator, ref actionRequired))
            {
                return;
            }
        }
    }

    // 0x08: PHP [0]
    // 0x28: PLP [0]
    // 0x48: PHA [0]
    private static void Step3(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
    }

    // 0x08: PHP [1]
    private static void Step4(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(0x0100 | emulator.S);
        emulator.data = (byte)(emulator.P | 0b00110000);
        emulator.S -= 0x01;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap0;
    }

    // 0x28: PLP [1]
    private static void Step7(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(0x0100 | emulator.S);
    }

    // 0x28: PLP [2]
    private static void Step8(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.S += 0x01;
        emulator.address = (ushort)(0x0100 | emulator.S);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x48: PHA [1]
    private static void Step11(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(0x0100 | emulator.S);
        emulator.data = emulator.A;
        emulator.S -= 0x01;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap0;
    }

    // 0x68: PLA [0]
    private static void Step13(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
    }

    // 0x68: PLA [1]
    private static void Step14(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(0x0100 | emulator.S);
    }

    // 0x68: PLA [2]
    private static void Step15(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.S += 0x01;
        emulator.address = (ushort)(0x0100 | emulator.S);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap5;
    }

    // 0xA9: LDA #n [0]
    private static void Step23(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap5;
    }
}
