//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace MrKWatkins.OakCpu.M6502;

public sealed unsafe partial class M6502InstructionEmulator
{
    private static bool HandleInterrupts(M6502InstructionEmulator emulator)
    {
        return false;
    }
}
