//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace MrKWatkins.OakCpu.M6502;
/// <summary>
/// Provides access to the M6502 registers.
/// </summary>
public abstract class M6502Registers
{
    /// <summary>
    /// Gets or sets the accumulator register.
    /// </summary>
    public abstract byte A { get; set; }

    /// <summary>
    /// Gets or sets the processor status register.
    /// </summary>
    public abstract byte P { get; set; }

    /// <summary>
    /// Gets or sets the program counter.
    /// </summary>
    public abstract ushort PC { get; set; }

    /// <summary>
    /// Gets or sets the stack pointer.
    /// </summary>
    public abstract byte S { get; set; }

    /// <summary>
    /// Gets or sets the X index register.
    /// </summary>
    public abstract byte X { get; set; }

    /// <summary>
    /// Gets or sets the Y index register.
    /// </summary>
    public abstract byte Y { get; set; }
}
