//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MrKWatkins.OakCpu.M6502;

public sealed unsafe partial class M6502StepEmulator
{
    /// <summary>
    /// Executes one M6502 T-state.
    /// </summary>
    /// <returns>
    /// The external action that the host must perform for the completed T-state.
    /// </returns>
    public ActionRequired Step()
    {
        var step = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(Steps), currentStep);
        currentStep = step.NextStep;
        var actionRequired = step.ActionRequired;
        if (step.Handler != default)
        {
            step.Handler(this, ref actionRequired);
        }

        return actionRequired;
    }

    private static void Error(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        throw new NotSupportedException("Opcode not supported");
    }

    // Opcode read [0]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void Step0(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
    }

    // Opcode read [1]
    private static void Step1(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.currentStep = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(emulator.opcodeStepTable), emulator.data);
        var selectedStep = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(Steps), emulator.currentStep);
        if (selectedStep.Overlap != default)
        {
            // Queue overlap step.
            emulator.overlapPipeline = selectedStep.Overlap;
            emulator.currentStep = selectedStep.NextStep;
            // Check interrupts at the instruction boundary.
            if (HandleInterrupts(emulator, ref actionRequired))
            {
                return;
            }
        }
    }

    // Halt cycle [0]
    private static void Step2(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        // Execute queued overlap.
        emulator.ExecuteOverlap();
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
    }

    // Halt cycle [1]
    private static void Step3(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.currentStep = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(emulator.opcodeStepTable), emulator.data);
        var selectedStep = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(Steps), emulator.currentStep);
        if (selectedStep.Overlap != default)
        {
            // Queue overlap step.
            emulator.overlapPipeline = selectedStep.Overlap;
            emulator.currentStep = selectedStep.NextStep;
            // Check interrupts at the instruction boundary.
            if (HandleInterrupts(emulator, ref actionRequired))
            {
                return;
            }
        }
    }

    // 0xA9: LDA #n [0]
    private static void Step4(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
    }

    // 0xA9: LDA #n [1]
    private static void Step5(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.A = emulator.data;

        // Update flags.
        int flags = emulator.P & 0b01011101; // Copy flag.C, flag.I, flag.D, flag.B and V from P.
        flags |= (Unsafe.BitCast<bool, byte>(emulator.A == 0)) << 1; // Set Z if is_zero(A) is true.
        flags |= emulator.A & 0b10000000; // Set N if is_negative(A) is true.
        emulator.P = (byte)flags;
        emulator.currentStep = 0;
    }
}
