//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;

namespace MrKWatkins.OakCpu.M6502;

public sealed unsafe partial class M6502StepEmulator
{
    private const ushort OpcodeReadStep0 = 0;

    private const ushort HaltedStep0 = 2;

    private const ushort IM0Step0 = 4;

    private static readonly Step[] Steps;

    private static readonly delegate*<M6502StepEmulator, void>[] Overlaps;

    private static readonly ushort[] OpcodeStepTableNoPrefix;

    private static readonly ushort[] InterruptModeStepTable;

    static M6502StepEmulator()
    {
        if (!BitConverter.IsLittleEndian)
        {
#pragma warning disable CA1065
            throw new NotSupportedException("Only little endian systems are supported.");
#pragma warning restore CA1065
        }

        Steps = 
        [
            new(&Step0, 1, ActionRequired.OpcodeRead, default), new(&Step1, 8, ActionRequired.None, default), new(&Step2, 3, ActionRequired.OpcodeRead, default), new(&Step3, 2, ActionRequired.None, default), new(default, 0, ActionRequired.None, default), 
            new(&Step4, 6, ActionRequired.MemoryRead, default), new(&Step5, 0, ActionRequired.None, default), new(default, 0, ActionRequired.None, &Overlap0), new(&Error, 0, ActionRequired.None, default)
        ];
        Overlaps = [default(delegate*<M6502StepEmulator, void>), &Overlap0];
        OpcodeStepTableNoPrefix = 
        [
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 5, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 7, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
            8, 8, 8, 8, 8, 8
        ];
        InterruptModeStepTable = [4];
    }
}
