//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MrKWatkins.OakCpu.M6502;

public sealed unsafe partial class M6502StepEmulator
{
    /// <summary>
    /// Executes one M6502 T-state.
    /// </summary>
    /// <returns>
    /// The external action that the host must perform for the completed T-state.
    /// </returns>
    public ActionRequired Step()
    {
        var step = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(Steps), currentStep);
        currentStep = step.NextStep;
        var actionRequired = step.ActionRequired;
        if (step.Handler != default)
        {
            step.Handler(this, ref actionRequired);
        }

        return actionRequired;
    }

    private static void Error(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        throw new NotSupportedException("Opcode not supported");
    }

    // Opcode read [0]
    // Halt cycle [0]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void Step0(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        // Execute queued overlap.
        emulator.ExecuteOverlap();
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
    }

    // Opcode read [1]
    private static void Step1(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.currentStep = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(emulator.opcodeStepTable), emulator.data);
        var selectedStep = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(Steps), emulator.currentStep);
        if (selectedStep.Overlap != default)
        {
            // Queue overlap step.
            emulator.overlapPipeline = selectedStep.Overlap;
            emulator.currentStep = selectedStep.NextStep;
            // Check interrupts at the instruction boundary.
            if (HandleInterrupts(emulator, ref actionRequired))
            {
                return;
            }
        }
    }

    // branch not taken finish [0]
    private static void Step2(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        // Finish instruction.
        emulator.currentStep = 0;
    }

    // branch taken finish [0]
    private static void Step3(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.PC = emulator.ad;
        // Finish instruction.
        emulator.currentStep = 0;
    }

    // branch page cross [0]
    private static void Step4(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.PC & 0xFF00 | emulator.ad & 0b11111111);
        emulator.currentStep = 3;
    }

    // ora finish [0]
    private static void Step5(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.A |= emulator.data;
        emulator.P &= 0x5D;
        if (emulator.A == 0)
        {
            emulator.P |= 0x02;
        }

        if (((emulator.A & 0b10000000) != 0x00))
        {
            emulator.P |= 0x80;
        }

        // Finish instruction.
        emulator.currentStep = 0;
    }

    // and finish [0]
    private static void Step6(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.A &= emulator.data;
        emulator.P &= 0x5D;
        if (emulator.A == 0)
        {
            emulator.P |= 0x02;
        }

        if (((emulator.A & 0b10000000) != 0x00))
        {
            emulator.P |= 0x80;
        }

        // Finish instruction.
        emulator.currentStep = 0;
    }

    // eor finish [0]
    private static void Step7(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.A ^= emulator.data;
        emulator.P &= 0x5D;
        if (emulator.A == 0)
        {
            emulator.P |= 0x02;
        }

        if (((emulator.A & 0b10000000) != 0x00))
        {
            emulator.P |= 0x80;
        }

        // Finish instruction.
        emulator.currentStep = 0;
    }

    // ldx finish [0]
    private static void Step8(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.X = emulator.data;
        emulator.P &= 0x5D;
        if (emulator.X == 0)
        {
            emulator.P |= 0x02;
        }

        if (((emulator.X & 0b10000000) != 0x00))
        {
            emulator.P |= 0x80;
        }

        // Finish instruction.
        emulator.currentStep = 0;
    }

    // lda finish [0]
    private static void Step9(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.A = emulator.data;
        emulator.P &= 0x5D;
        if (emulator.A == 0)
        {
            emulator.P |= 0x02;
        }

        if (((emulator.A & 0b10000000) != 0x00))
        {
            emulator.P |= 0x80;
        }

        // Finish instruction.
        emulator.currentStep = 0;
    }

    // ldy finish [0]
    private static void Step10(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.Y = emulator.data;
        emulator.P &= 0x5D;
        if (emulator.Y == 0)
        {
            emulator.P |= 0x02;
        }

        if (((emulator.Y & 0b10000000) != 0x00))
        {
            emulator.P |= 0x80;
        }

        // Finish instruction.
        emulator.currentStep = 0;
    }

    // cmp finish [0]
    private static void Step11(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.P &= 0x5C;
        if (emulator.A >= emulator.data)
        {
            emulator.P |= 0x01;
        }

        var result = emulator.A - emulator.data;
        if (result == 0)
        {
            emulator.P |= 0x02;
        }

        if (((result & 0b10000000) != 0x00))
        {
            emulator.P |= 0x80;
        }

        // Finish instruction.
        emulator.currentStep = 0;
    }

    // adc finish [0]
    private static void Step12(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        var carry = emulator.P & 0b00000001;
        var left = emulator.A;
        var right = emulator.data;
        var binary_result = left + right + carry;
        if (((emulator.P & 0b00001000) == 0b00001000 /* flag.D */))
        {
            var low = (left & 0b00001111) + (right & 0b00001111) + carry;
            var high = (left & 0b11110000) + (right & 0b11110000);
            emulator.P &= 0x1C;
            if ((binary_result & 0b11111111) == 0x00)
            {
                emulator.P |= 0x02;
            }

            if (low > 0x09)
            {
                high += 0x10;
                low += 0x06;
            }

            if (((high & 0b10000000) != 0x00))
            {
                emulator.P |= 0x80;
            }

            if ((((high ^ left) & (high ^ right) & 0b10000000) != 0x00))
            {
                emulator.P |= 0x40;
            }

            if (high > 0x90)
            {
                high += 0x60;
            }

            if (high > 0xFF)
            {
                emulator.P |= 0x01;
            }

            emulator.A = (byte)(low & 0b00001111 | high & 0b11110000);
        }
        else
        {
            emulator.A = (byte)binary_result;
            emulator.P &= 0x1C;
            if ((((binary_result ^ left) & (binary_result ^ right) & 0b10000000) != 0x00))
            {
                emulator.P |= 0x40;
            }

            if ((binary_result & 0x0100) != 0x00)
            {
                emulator.P |= 0x01;
            }

            if (emulator.A == 0)
            {
                emulator.P |= 0x02;
            }

            if (((emulator.A & 0b10000000) != 0x00))
            {
                emulator.P |= 0x80;
            }
        }

        // Finish instruction.
        emulator.currentStep = 0;
    }

    // sbc finish [0]
    private static void Step13(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        var borrow = 0x01 - (emulator.P & 0b00000001);
        var left = emulator.A;
        var right = emulator.data;
        var binary_result = left - right - borrow;
        if (((emulator.P & 0b00001000) == 0b00001000 /* flag.D */))
        {
            var low = (left & 0b00001111) - (right & 0b00001111) - borrow;
            var high = (left & 0b11110000) - (right & 0b11110000);
            emulator.P &= 0x1C;
            if ((low & 0b00010000) != 0x00)
            {
                low -= 0x06;
                high -= 0x10;
            }

            if ((((left ^ right) & (binary_result ^ left) & 0b10000000) != 0x00))
            {
                emulator.P |= 0x40;
            }

            if ((binary_result & 0x0100) == 0x00)
            {
                emulator.P |= 0x01;
            }

            if ((binary_result & 0b11111111) == 0x00)
            {
                emulator.P |= 0x02;
            }

            if (((binary_result & 0b10000000) != 0x00))
            {
                emulator.P |= 0x80;
            }

            if ((high & 0x0100) != 0x00)
            {
                high -= 0x60;
            }

            emulator.A = (byte)(low & 0b00001111 | high & 0b11110000);
        }
        else
        {
            emulator.A = (byte)binary_result;
            emulator.P &= 0x1C;
            if ((((left ^ right) & (binary_result ^ left) & 0b10000000) != 0x00))
            {
                emulator.P |= 0x40;
            }

            if ((binary_result & 0x0100) == 0x00)
            {
                emulator.P |= 0x01;
            }

            if (emulator.A == 0)
            {
                emulator.P |= 0x02;
            }

            if (((emulator.A & 0b10000000) != 0x00))
            {
                emulator.P |= 0x80;
            }
        }

        // Finish instruction.
        emulator.currentStep = 0;
    }

    // Halt cycle [1]
    private static void Step14(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.currentStep = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(emulator.opcodeStepTable), emulator.data);
        var selectedStep = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(Steps), emulator.currentStep);
        if (selectedStep.Overlap != default)
        {
            // Queue overlap step.
            emulator.overlapPipeline = selectedStep.Overlap;
            emulator.currentStep = selectedStep.NextStep;
            // Check interrupts at the instruction boundary.
            if (HandleInterrupts(emulator, ref actionRequired))
            {
                return;
            }
        }
    }

    // 0x00: BRK [0]
    // 0x06: ASL zp [0]
    // 0x0E: ASL abs [0]
    // 0x11: ORA (zp),Y [0]
    // 0x16: ASL zp,X [0]
    // 0x19: ORA abs,Y [0]
    // 0x1D: ORA abs,X [0]
    // 0x1E: ASL abs,X [0]
    // 0x20: JSR abs [0]
    // 0x26: ROL zp [0]
    // 0x2E: ROL abs [0]
    // 0x31: AND (zp),Y [0]
    // 0x36: ROL zp,X [0]
    // 0x39: AND abs,Y [0]
    // 0x3D: AND abs,X [0]
    // 0x3E: ROL abs,X [0]
    // 0x46: LSR zp [0]
    // 0x4C: JMP abs [0]
    // 0x4E: LSR abs [0]
    // 0x51: EOR (zp),Y [0]
    // 0x56: LSR zp,X [0]
    // 0x59: EOR abs,Y [0]
    // 0x5D: EOR abs,X [0]
    // 0x5E: LSR abs,X [0]
    // 0x61: ADC (zp,X) [0]
    // 0x65: ADC zp [0]
    // 0x66: ROR zp [0]
    // 0x6C: JMP (abs) [0]
    // 0x6D: ADC abs [0]
    // 0x6E: ROR abs [0]
    // 0x71: ADC (zp),Y [0]
    // 0x75: ADC zp,X [0]
    // 0x76: ROR zp,X [0]
    // 0x79: ADC abs,Y [0]
    // 0x7D: ADC abs,X [0]
    // 0x7E: ROR abs,X [0]
    // 0x81: STA (zp,X) [0]
    // 0x84: STY zp [0]
    // 0x85: STA zp [0]
    // 0x86: STX zp [0]
    // 0x8C: STY abs [0]
    // 0x8D: STA abs [0]
    // 0x8E: STX abs [0]
    // 0x91: STA (zp),Y [0]
    // 0x94: STY zp,X [0]
    // 0x95: STA zp,X [0]
    // 0x96: STX zp,Y [0]
    // 0x99: STA abs,Y [0]
    // 0x9D: STA abs,X [0]
    // 0xB1: LDA (zp),Y [0]
    // 0xB9: LDA abs,Y [0]
    // 0xBC: LDY abs,X [0]
    // 0xBD: LDA abs,X [0]
    // 0xBE: LDX abs,Y [0]
    // 0xC6: DEC zp [0]
    // 0xCE: DEC abs [0]
    // 0xD1: CMP (zp),Y [0]
    // 0xD6: DEC zp,X [0]
    // 0xD9: CMP abs,Y [0]
    // 0xDD: CMP abs,X [0]
    // 0xDE: DEC abs,X [0]
    // 0xE1: SBC (zp,X) [0]
    // 0xE5: SBC zp [0]
    // 0xE6: INC zp [0]
    // 0xED: SBC abs [0]
    // 0xEE: INC abs [0]
    // 0xF1: SBC (zp),Y [0]
    // 0xF5: SBC zp,X [0]
    // 0xF6: INC zp,X [0]
    // 0xF9: SBC abs,Y [0]
    // 0xFD: SBC abs,X [0]
    // 0xFE: INC abs,X [0]
    private static void Step15(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
    }

    // 0x00: BRK [1]
    // 0x20: JSR abs [2]
    private static void Step16(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(0x0100 | emulator.S);
        emulator.data = (byte)(emulator.PC >> 0x08);
        emulator.S -= 0x01;
    }

    // 0x00: BRK [2]
    // 0x20: JSR abs [3]
    private static void Step17(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(0x0100 | emulator.S);
        emulator.data = (byte)(emulator.PC & 0b11111111);
        emulator.S -= 0x01;
    }

    // 0x00: BRK [3]
    private static void Step18(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(0x0100 | emulator.S);
        emulator.data = (byte)(emulator.P | 0b00110000);
        emulator.P |= 0x04;
        emulator.S -= 0x01;
    }

    // 0x00: BRK [4]
    private static void Step19(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = 0xFFFE;
    }

    // 0x00: BRK [5]
    private static void Step20(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = 0xFFFF;
        emulator.ad = (ushort)emulator.data;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap0;
    }

    // 0x01: ORA (zp,X) [0]
    // 0x05: ORA zp [0]
    // 0x0D: ORA abs [0]
    // 0x15: ORA zp,X [0]
    // 0x21: AND (zp,X) [0]
    // 0x24: BIT zp [0]
    // 0x25: AND zp [0]
    // 0x2C: BIT abs [0]
    // 0x2D: AND abs [0]
    // 0x35: AND zp,X [0]
    // 0x41: EOR (zp,X) [0]
    // 0x45: EOR zp [0]
    // 0x4D: EOR abs [0]
    // 0x55: EOR zp,X [0]
    // 0xA1: LDA (zp,X) [0]
    // 0xA4: LDY zp [0]
    // 0xA5: LDA zp [0]
    // 0xA6: LDX zp [0]
    // 0xAC: LDY abs [0]
    // 0xAD: LDA abs [0]
    // 0xAE: LDX abs [0]
    // 0xB4: LDY zp,X [0]
    // 0xB5: LDA zp,X [0]
    // 0xB6: LDX zp,Y [0]
    // 0xC1: CMP (zp,X) [0]
    // 0xC4: CPY zp [0]
    // 0xC5: CMP zp [0]
    // 0xCC: CPY abs [0]
    // 0xCD: CMP abs [0]
    // 0xD5: CMP zp,X [0]
    // 0xE4: CPX zp [0]
    // 0xEC: CPX abs [0]
    private static void Step22(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
    }

    // 0x01: ORA (zp,X) [1]
    // 0x15: ORA zp,X [1]
    // 0x21: AND (zp,X) [1]
    // 0x35: AND zp,X [1]
    // 0x41: EOR (zp,X) [1]
    // 0x55: EOR zp,X [1]
    // 0xA1: LDA (zp,X) [1]
    // 0xB4: LDY zp,X [1]
    // 0xB5: LDA zp,X [1]
    // 0xB6: LDX zp,Y [1]
    // 0xC1: CMP (zp,X) [1]
    // 0xD5: CMP zp,X [1]
    private static void Step23(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)emulator.data;
        emulator.address = emulator.ad;
    }

    // 0x01: ORA (zp,X) [2]
    // 0x21: AND (zp,X) [2]
    // 0x41: EOR (zp,X) [2]
    // 0xA1: LDA (zp,X) [2]
    // 0xC1: CMP (zp,X) [2]
    private static void Step24(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.ad + emulator.X & 0b11111111);
        emulator.address = emulator.ad;
    }

    // 0x01: ORA (zp,X) [3]
    // 0x21: AND (zp,X) [3]
    // 0x41: EOR (zp,X) [3]
    // 0xA1: LDA (zp,X) [3]
    // 0xC1: CMP (zp,X) [3]
    private static void Step25(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + 0x01 & 0b11111111);
        emulator.ad = (ushort)emulator.data;
    }

    // 0x01: ORA (zp,X) [4]
    // 0x0D: ORA abs [2]
    private static void Step26(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap1;
    }

    // 0x05: ORA zp [1]
    private static void Step28(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)emulator.data;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap1;
    }

    // 0x06: ASL zp [1]
    // 0x26: ROL zp [1]
    // 0x46: LSR zp [1]
    // 0x66: ROR zp [1]
    // 0xC6: DEC zp [1]
    // 0xE6: INC zp [1]
    private static void Step29(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)emulator.data;
    }

    // 0x06: ASL zp [2]
    // 0x0E: ASL abs [3]
    // 0x16: ASL zp,X [3]
    // 0x1E: ASL abs,X [4]
    // 0x26: ROL zp [2]
    // 0x2E: ROL abs [3]
    // 0x36: ROL zp,X [3]
    // 0x3E: ROL abs,X [4]
    // 0x46: LSR zp [2]
    // 0x4E: LSR abs [3]
    // 0x56: LSR zp,X [3]
    // 0x5E: LSR abs,X [4]
    // 0x66: ROR zp [2]
    // 0x6E: ROR abs [3]
    // 0x76: ROR zp,X [3]
    // 0x7E: ROR abs,X [4]
    // 0xC6: DEC zp [2]
    // 0xCE: DEC abs [3]
    // 0xD6: DEC zp,X [3]
    // 0xDE: DEC abs,X [4]
    // 0xE6: INC zp [2]
    // 0xEE: INC abs [3]
    // 0xF6: INC zp,X [3]
    // 0xFE: INC abs,X [4]
    private static void Step30(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
    }

    // 0x06: ASL zp [3]
    // 0x0E: ASL abs [4]
    // 0x16: ASL zp,X [4]
    // 0x1E: ASL abs,X [5]
    private static void Step31(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        var value = emulator.data;
        emulator.data = (byte)(value << 0x01 & 0b11111111);
        emulator.P &= 0x7C;
        if (emulator.data == 0)
        {
            emulator.P |= 0x02;
        }

        if (((emulator.data & 0b10000000) != 0x00))
        {
            emulator.P |= 0x80;
        }

        if (((value & 0b10000000) != 0x00))
        {
            emulator.P |= 0x01;
        }

        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x08: PHP [0]
    // 0x28: PLP [0]
    // 0x40: RTI [0]
    // 0x48: PHA [0]
    // 0x60: RTS [0]
    private static void Step33(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
    }

    // 0x08: PHP [1]
    private static void Step34(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(0x0100 | emulator.S);
        emulator.data = (byte)(emulator.P | 0b00110000);
        emulator.S -= 0x01;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x09: ORA #n [0]
    private static void Step35(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap1;
    }

    // 0x0D: ORA abs [1]
    // 0x2C: BIT abs [1]
    // 0x2D: AND abs [1]
    // 0x4D: EOR abs [1]
    // 0xAC: LDY abs [1]
    // 0xAD: LDA abs [1]
    // 0xAE: LDX abs [1]
    // 0xCC: CPY abs [1]
    // 0xCD: CMP abs [1]
    // 0xEC: CPX abs [1]
    private static void Step37(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        emulator.ad = (ushort)emulator.data;
    }

    // 0x0E: ASL abs [1]
    // 0x19: ORA abs,Y [1]
    // 0x1D: ORA abs,X [1]
    // 0x1E: ASL abs,X [1]
    // 0x2E: ROL abs [1]
    // 0x39: AND abs,Y [1]
    // 0x3D: AND abs,X [1]
    // 0x3E: ROL abs,X [1]
    // 0x4E: LSR abs [1]
    // 0x59: EOR abs,Y [1]
    // 0x5D: EOR abs,X [1]
    // 0x5E: LSR abs,X [1]
    // 0x6C: JMP (abs) [1]
    // 0x6D: ADC abs [1]
    // 0x6E: ROR abs [1]
    // 0x79: ADC abs,Y [1]
    // 0x7D: ADC abs,X [1]
    // 0x7E: ROR abs,X [1]
    // 0x8C: STY abs [1]
    // 0x8D: STA abs [1]
    // 0x8E: STX abs [1]
    // 0x99: STA abs,Y [1]
    // 0x9D: STA abs,X [1]
    // 0xB9: LDA abs,Y [1]
    // 0xBC: LDY abs,X [1]
    // 0xBD: LDA abs,X [1]
    // 0xBE: LDX abs,Y [1]
    // 0xCE: DEC abs [1]
    // 0xD9: CMP abs,Y [1]
    // 0xDD: CMP abs,X [1]
    // 0xDE: DEC abs,X [1]
    // 0xED: SBC abs [1]
    // 0xEE: INC abs [1]
    // 0xF9: SBC abs,Y [1]
    // 0xFD: SBC abs,X [1]
    // 0xFE: INC abs,X [1]
    private static void Step38(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        emulator.ad = (ushort)emulator.data;
    }

    // 0x0E: ASL abs [2]
    // 0x2E: ROL abs [2]
    // 0x4E: LSR abs [2]
    // 0x6E: ROR abs [2]
    // 0xCE: DEC abs [2]
    // 0xEE: INC abs [2]
    private static void Step39(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
    }

    // 0x10: BPL [0]
    private static void Step40(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        if (((emulator.P & 0b10000000) == 0b10000000 /* flag.N */))
        {
            emulator.currentStep = 2;
        }
    }

    // 0x10: BPL [1]
    // 0x30: BMI [1]
    // 0x50: BVC [1]
    // 0x70: BVS [1]
    // 0x90: BCC [1]
    // 0xB0: BCS [1]
    // 0xD0: BNE [1]
    // 0xF0: BEQ [1]
    private static void Step41(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.PC + (sbyte)emulator.data);
        emulator.address = emulator.PC;
        if ((emulator.ad & 0xFF00) != (emulator.PC & 0xFF00))
        {
            emulator.currentStep = 4;
        }
        else
        {
            emulator.currentStep = 3;
        }
    }

    // 0x11: ORA (zp),Y [1]
    // 0x16: ASL zp,X [1]
    // 0x31: AND (zp),Y [1]
    // 0x36: ROL zp,X [1]
    // 0x51: EOR (zp),Y [1]
    // 0x56: LSR zp,X [1]
    // 0x61: ADC (zp,X) [1]
    // 0x71: ADC (zp),Y [1]
    // 0x75: ADC zp,X [1]
    // 0x76: ROR zp,X [1]
    // 0x81: STA (zp,X) [1]
    // 0x91: STA (zp),Y [1]
    // 0x94: STY zp,X [1]
    // 0x95: STA zp,X [1]
    // 0x96: STX zp,Y [1]
    // 0xB1: LDA (zp),Y [1]
    // 0xD1: CMP (zp),Y [1]
    // 0xD6: DEC zp,X [1]
    // 0xE1: SBC (zp,X) [1]
    // 0xF1: SBC (zp),Y [1]
    // 0xF5: SBC zp,X [1]
    // 0xF6: INC zp,X [1]
    private static void Step42(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)emulator.data;
        emulator.address = emulator.ad;
    }

    // 0x11: ORA (zp),Y [2]
    // 0x31: AND (zp),Y [2]
    // 0x51: EOR (zp),Y [2]
    // 0x61: ADC (zp,X) [3]
    // 0x71: ADC (zp),Y [2]
    // 0x81: STA (zp,X) [3]
    // 0x91: STA (zp),Y [2]
    // 0xB1: LDA (zp),Y [2]
    // 0xD1: CMP (zp),Y [2]
    // 0xE1: SBC (zp,X) [3]
    // 0xF1: SBC (zp),Y [2]
    private static void Step43(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + 0x01 & 0b11111111);
        emulator.ad = (ushort)emulator.data;
    }

    // 0x11: ORA (zp),Y [3]
    private static void Step44(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.ad | emulator.data << 0x08);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.Y > 0xFF))
        {
            emulator.currentStep = 5;
        }
    }

    // 0x11: ORA (zp),Y [4]
    // 0x19: ORA abs,Y [3]
    private static void Step45(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.Y);
        emulator.currentStep = 5;
    }

    // 0x15: ORA zp,X [2]
    private static void Step46(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X & 0b11111111);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap1;
    }

    // 0x16: ASL zp,X [2]
    // 0x36: ROL zp,X [2]
    // 0x56: LSR zp,X [2]
    // 0x76: ROR zp,X [2]
    // 0xD6: DEC zp,X [2]
    // 0xF6: INC zp,X [2]
    private static void Step47(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X & 0b11111111);
    }

    // 0x19: ORA abs,Y [2]
    private static void Step49(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.Y > 0xFF))
        {
            emulator.currentStep = 5;
        }
    }

    // 0x1D: ORA abs,X [2]
    private static void Step50(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.X & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.X > 0xFF))
        {
            emulator.currentStep = 5;
        }
    }

    // 0x1D: ORA abs,X [3]
    private static void Step51(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X);
        emulator.currentStep = 5;
    }

    // 0x1E: ASL abs,X [2]
    // 0x3E: ROL abs,X [2]
    // 0x5E: LSR abs,X [2]
    // 0x7E: ROR abs,X [2]
    // 0x9D: STA abs,X [2]
    // 0xDE: DEC abs,X [2]
    // 0xFE: INC abs,X [2]
    private static void Step52(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.X & 0b11111111);
    }

    // 0x1E: ASL abs,X [3]
    // 0x3E: ROL abs,X [3]
    // 0x5E: LSR abs,X [3]
    // 0x7E: ROR abs,X [3]
    // 0xDE: DEC abs,X [3]
    // 0xFE: INC abs,X [3]
    private static void Step53(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X);
    }

    // 0x20: JSR abs [1]
    private static void Step54(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)emulator.data;
        emulator.address = (ushort)(0x0100 | emulator.S);
    }

    // 0x20: JSR abs [4]
    private static void Step55(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap0;
    }

    // 0x21: AND (zp,X) [4]
    // 0x2D: AND abs [2]
    private static void Step56(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap5;
    }

    // 0x24: BIT zp [1]
    private static void Step58(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)emulator.data;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap6;
    }

    // 0x25: AND zp [1]
    private static void Step60(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)emulator.data;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap5;
    }

    // 0x26: ROL zp [3]
    // 0x2E: ROL abs [4]
    // 0x36: ROL zp,X [4]
    // 0x3E: ROL abs,X [5]
    private static void Step61(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        var carry = emulator.P & 0b00000001;
        var value = emulator.data;
        emulator.data = (byte)((value << 0x01 | carry) & 0b11111111);
        emulator.P &= 0x7C;
        if (emulator.data == 0)
        {
            emulator.P |= 0x02;
        }

        if (((emulator.data & 0b10000000) != 0x00))
        {
            emulator.P |= 0x80;
        }

        if (((value & 0b10000000) != 0x00))
        {
            emulator.P |= 0x01;
        }

        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x28: PLP [1]
    // 0x40: RTI [1]
    // 0x60: RTS [1]
    private static void Step62(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(0x0100 | emulator.S);
    }

    // 0x28: PLP [2]
    private static void Step63(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.S += 0x01;
        emulator.address = (ushort)(0x0100 | emulator.S);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap7;
    }

    // 0x29: AND #n [0]
    private static void Step65(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap5;
    }

    // 0x2C: BIT abs [2]
    private static void Step67(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap6;
    }

    // 0x30: BMI [0]
    private static void Step68(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        if (!((emulator.P & 0b10000000) == 0b10000000 /* flag.N */))
        {
            emulator.currentStep = 2;
        }
    }

    // 0x31: AND (zp),Y [3]
    private static void Step69(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.ad | emulator.data << 0x08);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.Y > 0xFF))
        {
            emulator.currentStep = 6;
        }
    }

    // 0x31: AND (zp),Y [4]
    // 0x39: AND abs,Y [3]
    private static void Step70(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.Y);
        emulator.currentStep = 6;
    }

    // 0x35: AND zp,X [2]
    private static void Step71(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X & 0b11111111);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap5;
    }

    // 0x39: AND abs,Y [2]
    private static void Step73(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.Y > 0xFF))
        {
            emulator.currentStep = 6;
        }
    }

    // 0x3D: AND abs,X [2]
    private static void Step74(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.X & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.X > 0xFF))
        {
            emulator.currentStep = 6;
        }
    }

    // 0x3D: AND abs,X [3]
    private static void Step75(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X);
        emulator.currentStep = 6;
    }

    // 0x40: RTI [2]
    // 0x60: RTS [2]
    private static void Step76(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.S += 0x01;
        emulator.address = (ushort)(0x0100 | emulator.S);
    }

    // 0x40: RTI [3]
    private static void Step77(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.S += 0x01;
        emulator.P = (byte)(emulator.data & 0b11101111 | 0b00100000);
        emulator.address = (ushort)(0x0100 | emulator.S);
    }

    // 0x40: RTI [4]
    private static void Step78(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.S += 0x01;
        emulator.ad = (ushort)emulator.data;
        emulator.address = (ushort)(0x0100 | emulator.S);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap0;
    }

    // 0x41: EOR (zp,X) [4]
    // 0x4D: EOR abs [2]
    private static void Step79(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap10;
    }

    // 0x45: EOR zp [1]
    private static void Step81(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)emulator.data;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap10;
    }

    // 0x46: LSR zp [3]
    // 0x4E: LSR abs [4]
    // 0x56: LSR zp,X [4]
    // 0x5E: LSR abs,X [5]
    private static void Step82(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        var value = emulator.data;
        emulator.data = (byte)(value >> 0x01);
        emulator.P &= 0x7C;
        if (emulator.data == 0)
        {
            emulator.P |= 0x02;
        }

        if ((value & 0b00000001) != 0x00)
        {
            emulator.P |= 0x01;
        }

        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x48: PHA [1]
    private static void Step83(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(0x0100 | emulator.S);
        emulator.data = emulator.A;
        emulator.S -= 0x01;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x49: EOR #n [0]
    private static void Step84(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap10;
    }

    // 0x4C: JMP abs [1]
    private static void Step86(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        emulator.ad = (ushort)emulator.data;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap0;
    }

    // 0x50: BVC [0]
    private static void Step87(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        if (((emulator.P & 0b01000000) == 0b01000000 /* flag.V */))
        {
            emulator.currentStep = 2;
        }
    }

    // 0x51: EOR (zp),Y [3]
    private static void Step88(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.ad | emulator.data << 0x08);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.Y > 0xFF))
        {
            emulator.currentStep = 7;
        }
    }

    // 0x51: EOR (zp),Y [4]
    // 0x59: EOR abs,Y [3]
    private static void Step89(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.Y);
        emulator.currentStep = 7;
    }

    // 0x55: EOR zp,X [2]
    private static void Step90(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X & 0b11111111);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap10;
    }

    // 0x59: EOR abs,Y [2]
    private static void Step92(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.Y > 0xFF))
        {
            emulator.currentStep = 7;
        }
    }

    // 0x5D: EOR abs,X [2]
    private static void Step93(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.X & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.X > 0xFF))
        {
            emulator.currentStep = 7;
        }
    }

    // 0x5D: EOR abs,X [3]
    private static void Step94(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X);
        emulator.currentStep = 7;
    }

    // 0x60: RTS [3]
    private static void Step95(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.S += 0x01;
        emulator.ad = (ushort)emulator.data;
        emulator.address = (ushort)(0x0100 | emulator.S);
    }

    // 0x60: RTS [4]
    private static void Step96(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.ad = emulator.address;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap13;
    }

    // 0x61: ADC (zp,X) [2]
    // 0x81: STA (zp,X) [2]
    // 0xE1: SBC (zp,X) [2]
    private static void Step98(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.ad + emulator.X & 0b11111111);
        emulator.address = emulator.ad;
    }

    // 0x61: ADC (zp,X) [4]
    // 0x6D: ADC abs [2]
    private static void Step99(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap14;
    }

    // 0x65: ADC zp [1]
    private static void Step101(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)emulator.data;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap14;
    }

    // 0x66: ROR zp [3]
    // 0x6E: ROR abs [4]
    // 0x76: ROR zp,X [4]
    // 0x7E: ROR abs,X [5]
    private static void Step102(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        var carry = emulator.P & 0b00000001;
        var value = emulator.data;
        emulator.data = (byte)((value >> 0x01 | carry << 0x07) & 0b11111111);
        emulator.P &= 0x7C;
        if (emulator.data == 0)
        {
            emulator.P |= 0x02;
        }

        if (((emulator.data & 0b10000000) != 0x00))
        {
            emulator.P |= 0x80;
        }

        if ((value & 0b00000001) != 0x00)
        {
            emulator.P |= 0x01;
        }

        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x68: PLA [0]
    private static void Step103(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
    }

    // 0x68: PLA [1]
    private static void Step104(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(0x0100 | emulator.S);
    }

    // 0x68: PLA [2]
    private static void Step105(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.S += 0x01;
        emulator.address = (ushort)(0x0100 | emulator.S);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap15;
    }

    // 0x69: ADC #n [0]
    private static void Step107(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap14;
    }

    // 0x6C: JMP (abs) [2]
    private static void Step109(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.ad | emulator.data << 0x08);
        emulator.address = emulator.ad;
    }

    // 0x6C: JMP (abs) [3]
    private static void Step110(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + 0x01 & 0b11111111);
        emulator.ad = (ushort)emulator.data;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap0;
    }

    // 0x70: BVS [0]
    private static void Step111(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        if (!((emulator.P & 0b01000000) == 0b01000000 /* flag.V */))
        {
            emulator.currentStep = 2;
        }
    }

    // 0x71: ADC (zp),Y [3]
    private static void Step112(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.ad | emulator.data << 0x08);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.Y > 0xFF))
        {
            emulator.currentStep = 12;
        }
    }

    // 0x71: ADC (zp),Y [4]
    // 0x79: ADC abs,Y [3]
    private static void Step113(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.Y);
        emulator.currentStep = 12;
    }

    // 0x75: ADC zp,X [2]
    private static void Step114(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X & 0b11111111);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap14;
    }

    // 0x79: ADC abs,Y [2]
    private static void Step116(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.Y > 0xFF))
        {
            emulator.currentStep = 12;
        }
    }

    // 0x7D: ADC abs,X [2]
    private static void Step117(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.X & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.X > 0xFF))
        {
            emulator.currentStep = 12;
        }
    }

    // 0x7D: ADC abs,X [3]
    private static void Step118(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X);
        emulator.currentStep = 12;
    }

    // 0x81: STA (zp,X) [4]
    // 0x8D: STA abs [2]
    private static void Step119(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.data = emulator.A;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x84: STY zp [1]
    private static void Step120(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)emulator.data;
        emulator.data = emulator.Y;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x85: STA zp [1]
    private static void Step121(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)emulator.data;
        emulator.data = emulator.A;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x86: STX zp [1]
    private static void Step122(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)emulator.data;
        emulator.data = emulator.X;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x8C: STY abs [2]
    private static void Step125(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.data = emulator.Y;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x8E: STX abs [2]
    private static void Step126(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.data = emulator.X;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x90: BCC [0]
    private static void Step127(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        if (((emulator.P & 0b00000001) == 0b00000001 /* flag.C */))
        {
            emulator.currentStep = 2;
        }
    }

    // 0x91: STA (zp),Y [3]
    private static void Step128(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.ad | emulator.data << 0x08);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
    }

    // 0x91: STA (zp),Y [4]
    // 0x99: STA abs,Y [3]
    private static void Step129(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.Y);
        emulator.data = emulator.A;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x94: STY zp,X [2]
    private static void Step130(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X & 0b11111111);
        emulator.data = emulator.Y;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x95: STA zp,X [2]
    private static void Step131(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X & 0b11111111);
        emulator.data = emulator.A;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x96: STX zp,Y [2]
    private static void Step132(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.Y & 0b11111111);
        emulator.data = emulator.X;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0x99: STA abs,Y [2]
    private static void Step134(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
    }

    // 0x9D: STA abs,X [3]
    private static void Step136(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X);
        emulator.data = emulator.A;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0xA0: LDY #n [0]
    private static void Step137(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap22;
    }

    // 0xA1: LDA (zp,X) [4]
    // 0xAD: LDA abs [2]
    private static void Step139(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap15;
    }

    // 0xA2: LDX #n [0]
    private static void Step140(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap23;
    }

    // 0xA4: LDY zp [1]
    private static void Step142(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)emulator.data;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap22;
    }

    // 0xA5: LDA zp [1]
    private static void Step143(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)emulator.data;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap15;
    }

    // 0xA6: LDX zp [1]
    private static void Step144(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)emulator.data;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap23;
    }

    // 0xA9: LDA #n [0]
    private static void Step146(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap15;
    }

    // 0xAC: LDY abs [2]
    private static void Step148(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap22;
    }

    // 0xAE: LDX abs [2]
    private static void Step149(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap23;
    }

    // 0xB0: BCS [0]
    private static void Step150(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        if (!((emulator.P & 0b00000001) == 0b00000001 /* flag.C */))
        {
            emulator.currentStep = 2;
        }
    }

    // 0xB1: LDA (zp),Y [3]
    private static void Step151(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.ad | emulator.data << 0x08);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.Y > 0xFF))
        {
            emulator.currentStep = 9;
        }
    }

    // 0xB1: LDA (zp),Y [4]
    // 0xB9: LDA abs,Y [3]
    private static void Step152(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.Y);
        emulator.currentStep = 9;
    }

    // 0xB4: LDY zp,X [2]
    private static void Step153(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X & 0b11111111);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap22;
    }

    // 0xB5: LDA zp,X [2]
    private static void Step154(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X & 0b11111111);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap15;
    }

    // 0xB6: LDX zp,Y [2]
    private static void Step155(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.Y & 0b11111111);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap23;
    }

    // 0xB9: LDA abs,Y [2]
    private static void Step157(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.Y > 0xFF))
        {
            emulator.currentStep = 9;
        }
    }

    // 0xBC: LDY abs,X [2]
    private static void Step159(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.X & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.X > 0xFF))
        {
            emulator.currentStep = 10;
        }
    }

    // 0xBC: LDY abs,X [3]
    private static void Step160(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X);
        emulator.currentStep = 10;
    }

    // 0xBD: LDA abs,X [2]
    private static void Step161(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.X & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.X > 0xFF))
        {
            emulator.currentStep = 9;
        }
    }

    // 0xBD: LDA abs,X [3]
    private static void Step162(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X);
        emulator.currentStep = 9;
    }

    // 0xBE: LDX abs,Y [2]
    private static void Step163(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.Y > 0xFF))
        {
            emulator.currentStep = 8;
        }
    }

    // 0xBE: LDX abs,Y [3]
    private static void Step164(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.Y);
        emulator.currentStep = 8;
    }

    // 0xC0: CPY #n [0]
    private static void Step165(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap28;
    }

    // 0xC1: CMP (zp,X) [4]
    // 0xCD: CMP abs [2]
    private static void Step167(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap29;
    }

    // 0xC4: CPY zp [1]
    private static void Step169(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)emulator.data;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap28;
    }

    // 0xC5: CMP zp [1]
    private static void Step170(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)emulator.data;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap29;
    }

    // 0xC6: DEC zp [3]
    // 0xCE: DEC abs [4]
    // 0xD6: DEC zp,X [4]
    // 0xDE: DEC abs,X [5]
    private static void Step171(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.data = (byte)(emulator.data - 0x01 & 0b11111111);
        emulator.P &= 0x7D;
        if (emulator.data == 0)
        {
            emulator.P |= 0x02;
        }

        if (((emulator.data & 0b10000000) != 0x00))
        {
            emulator.P |= 0x80;
        }

        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0xC9: CMP #n [0]
    private static void Step173(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap29;
    }

    // 0xCC: CPY abs [2]
    private static void Step175(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap28;
    }

    // 0xD0: BNE [0]
    private static void Step176(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        if (((emulator.P & 0b00000010) == 0b00000010 /* flag.Z */))
        {
            emulator.currentStep = 2;
        }
    }

    // 0xD1: CMP (zp),Y [3]
    private static void Step177(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.ad | emulator.data << 0x08);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.Y > 0xFF))
        {
            emulator.currentStep = 11;
        }
    }

    // 0xD1: CMP (zp),Y [4]
    // 0xD9: CMP abs,Y [3]
    private static void Step178(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.Y);
        emulator.currentStep = 11;
    }

    // 0xD5: CMP zp,X [2]
    private static void Step179(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X & 0b11111111);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap29;
    }

    // 0xD9: CMP abs,Y [2]
    private static void Step181(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.Y > 0xFF))
        {
            emulator.currentStep = 11;
        }
    }

    // 0xDD: CMP abs,X [2]
    private static void Step182(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.X & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.X > 0xFF))
        {
            emulator.currentStep = 11;
        }
    }

    // 0xDD: CMP abs,X [3]
    private static void Step183(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X);
        emulator.currentStep = 11;
    }

    // 0xE0: CPX #n [0]
    private static void Step184(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap33;
    }

    // 0xE1: SBC (zp,X) [4]
    // 0xED: SBC abs [2]
    private static void Step186(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap34;
    }

    // 0xE4: CPX zp [1]
    private static void Step188(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)emulator.data;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap33;
    }

    // 0xE5: SBC zp [1]
    private static void Step189(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)emulator.data;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap34;
    }

    // 0xE6: INC zp [3]
    // 0xEE: INC abs [4]
    // 0xF6: INC zp,X [4]
    // 0xFE: INC abs,X [5]
    private static void Step190(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.data = (byte)(emulator.data + 0x01 & 0b11111111);
        emulator.P &= 0x7D;
        if (emulator.data == 0)
        {
            emulator.P |= 0x02;
        }

        if (((emulator.data & 0b10000000) != 0x00))
        {
            emulator.P |= 0x80;
        }

        // Queue overlap step.
        emulator.overlapPipeline = &Overlap2;
    }

    // 0xE9: SBC #n [0]
    private static void Step192(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap34;
    }

    // 0xEC: CPX abs [2]
    private static void Step193(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.data << 0x08 | emulator.ad);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap33;
    }

    // 0xF0: BEQ [0]
    private static void Step194(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        if (!((emulator.P & 0b00000010) == 0b00000010 /* flag.Z */))
        {
            emulator.currentStep = 2;
        }
    }

    // 0xF1: SBC (zp),Y [3]
    private static void Step195(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.ad | emulator.data << 0x08);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.Y > 0xFF))
        {
            emulator.currentStep = 13;
        }
    }

    // 0xF1: SBC (zp),Y [4]
    // 0xF9: SBC abs,Y [3]
    private static void Step196(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.Y);
        emulator.currentStep = 13;
    }

    // 0xF5: SBC zp,X [2]
    private static void Step197(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X & 0b11111111);
        // Queue overlap step.
        emulator.overlapPipeline = &Overlap34;
    }

    // 0xF9: SBC abs,Y [2]
    private static void Step199(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.Y & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.Y > 0xFF))
        {
            emulator.currentStep = 13;
        }
    }

    // 0xFD: SBC abs,X [2]
    private static void Step200(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.ad = (ushort)(emulator.data << 0x08 | emulator.ad);
        emulator.address = (ushort)(emulator.ad & 0xFF00 | emulator.ad + emulator.X & 0b11111111);
        if (!((emulator.ad & 0b11111111) + emulator.X > 0xFF))
        {
            emulator.currentStep = 13;
        }
    }

    // 0xFD: SBC abs,X [3]
    private static void Step201(M6502StepEmulator emulator, ref ActionRequired actionRequired)
    {
        emulator.address = (ushort)(emulator.ad + emulator.X);
        emulator.currentStep = 13;
    }
}
