//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.IO;
using System.Text;

namespace MrKWatkins.OakCpu.M6502;

public sealed unsafe partial class M6502InstructionEmulator
{
    /// <summary>
    /// Serializes this emulator's M6502 CPU state.
    /// </summary>
    /// <param name="stream">
    /// The stream to write the CPU state to.
    /// </param>
    public void Serialize(Stream stream)
    {
        using var writer = new BinaryWriter(stream, Encoding.UTF8, true);
        if (opcodeStepTable == OpcodeStepTableNoPrefix)
        {
            writer.Write((byte)0);
        }

        writer.Write(address);
        writer.Write(data);
        writer.Write(nextSequenceStep);
        writer.Write(PCL);
        writer.Write(PCH);
        writer.Write(A);
        writer.Write(P);
        writer.Write(S);
        writer.Write(X);
        writer.Write(Y);
    }

    /// <summary>
    /// Deserializes a M6502 CPU state.
    /// </summary>
    /// <param name="stream">
    /// The stream to read the CPU state from.
    /// </param>
    /// <returns>
    /// The deserialized M6502 emulator.
    /// </returns>
    public static M6502InstructionEmulator Deserialize(Stream stream)
    {
        var deserialized = new M6502InstructionEmulator();
        deserialized.Restore(stream);
        return deserialized;
    }

    /// <summary>
    /// Restores this emulator from a serialized M6502 CPU state.
    /// </summary>
    /// <param name="stream">
    /// The stream to read the CPU state from.
    /// </param>
    public void Restore(Stream stream)
    {
        using var reader = new BinaryReader(stream, Encoding.UTF8, true);
        opcodeStepTable = reader.ReadByte() switch
        {
            0 => OpcodeStepTableNoPrefix,
            _ => throw new InvalidOperationException("Unknown opcode step table.")
        };
        address = reader.ReadUInt16();
        data = reader.ReadByte();
        nextSequenceStep = reader.ReadUInt16();
        PCL = reader.ReadByte();
        PCH = reader.ReadByte();
        A = reader.ReadByte();
        P = reader.ReadByte();
        S = reader.ReadByte();
        X = reader.ReadByte();
        Y = reader.ReadByte();
    }
}
