//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace MrKWatkins.OakCpu.M6502;

internal sealed class M6502StepInterrupts : M6502Interrupts
{
    private readonly M6502StepEmulator emulator;

    internal M6502StepInterrupts(M6502StepEmulator emulator)
    {
        this.emulator = emulator;
    }
}
