//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;

namespace MrKWatkins.OakCpu.M6502;

public sealed unsafe partial class M6502InstructionEmulator
{
    private static readonly delegate*<M6502InstructionEmulator, Action<ActionRequired, ushort, byte>, int>[] Instructions;

    private static readonly ushort[] OpcodeStepTableNoPrefix;

    private static readonly ushort[] InterruptModeStepTable;

    static M6502InstructionEmulator()
    {
        if (!BitConverter.IsLittleEndian)
        {
#pragma warning disable CA1065
            throw new NotSupportedException("Only little endian systems are supported.");
#pragma warning restore CA1065
        }

        Instructions = 
        [
            &Opcode_read, &branch_not_taken_finish, &branch_taken_finish, &branch_page_cross, &ora_finish, 
            &and_finish, &eor_finish, &ldx_finish, &lda_finish, &ldy_finish, 
            &cmp_finish, &adc_finish, &sbc_finish, &Halt_cycle, &Interrupt_Mode_0, 
            &BRK, &ORA_zp_X, &ORA_zp, &ASL_zp, &PHP, 
            &ORA_n, &ASL_A, &ORA_abs, &ASL_abs, &BPL, 
            &ORA_zp_Y, &ORA_zp_X_15, &ASL_zp_X, &CLC, &ORA_abs_Y, 
            &ORA_abs_X, &ASL_abs_X, &JSR_abs, &AND_zp_X, &BIT_zp, 
            &AND_zp, &ROL_zp, &PLP, &AND_n, &ROL_A, 
            &BIT_abs, &AND_abs, &ROL_abs, &BMI, &AND_zp_Y, 
            &AND_zp_X_35, &ROL_zp_X, &SEC, &AND_abs_Y, &AND_abs_X, 
            &ROL_abs_X, &RTI, &EOR_zp_X, &EOR_zp, &LSR_zp, 
            &PHA, &EOR_n, &LSR_A, &JMP_abs, &EOR_abs, 
            &LSR_abs, &BVC, &EOR_zp_Y, &EOR_zp_X_55, &LSR_zp_X, 
            &CLI, &EOR_abs_Y, &EOR_abs_X, &LSR_abs_X, &RTS, 
            &ADC_zp_X, &ADC_zp, &ROR_zp, &PLA, &ADC_n, 
            &ROR_A, &JMP_abs_6C, &ADC_abs, &ROR_abs, &BVS, 
            &ADC_zp_Y, &ADC_zp_X_75, &ROR_zp_X, &SEI, &ADC_abs_Y, 
            &ADC_abs_X, &ROR_abs_X, &STA_zp_X, &STY_zp, &STA_zp, 
            &STX_zp, &DEY, &TXA, &STY_abs, &STA_abs, 
            &STX_abs, &BCC, &STA_zp_Y, &STY_zp_X, &STA_zp_X_95, 
            &STX_zp_Y, &TYA, &STA_abs_Y, &TXS, &STA_abs_X, 
            &LDY_n, &LDA_zp_X, &LDX_n, &LDY_zp, &LDA_zp, 
            &LDX_zp, &TAY, &LDA_n, &TAX, &LDY_abs, 
            &LDA_abs, &LDX_abs, &BCS, &LDA_zp_Y, &LDY_zp_X, 
            &LDA_zp_X_B5, &LDX_zp_Y, &CLV, &LDA_abs_Y, &TSX, 
            &LDY_abs_X, &LDA_abs_X, &LDX_abs_Y, &CPY_n, &CMP_zp_X, 
            &CPY_zp, &CMP_zp, &DEC_zp, &INY, &CMP_n, 
            &DEX, &CPY_abs, &CMP_abs, &DEC_abs, &BNE, 
            &CMP_zp_Y, &CMP_zp_X_D5, &DEC_zp_X, &CLD, &CMP_abs_Y, 
            &CMP_abs_X, &DEC_abs_X, &CPX_n, &SBC_zp_X, &CPX_zp, 
            &SBC_zp, &INC_zp, &INX, &SBC_n, &NOP, 
            &CPX_abs, &SBC_abs, &INC_abs, &BEQ, &SBC_zp_Y, 
            &SBC_zp_X_F5, &INC_zp_X, &SED, &SBC_abs_Y, &SBC_abs_X, 
            &INC_abs_X, &Error
        ];
        OpcodeStepTableNoPrefix = 
        [
            15, 16, 166, 166, 166, 17, 18, 166, 19, 20, 
            21, 166, 166, 22, 23, 166, 24, 25, 166, 166, 
            166, 26, 27, 166, 28, 29, 166, 166, 166, 30, 
            31, 166, 32, 33, 166, 166, 34, 35, 36, 166, 
            37, 38, 39, 166, 40, 41, 42, 166, 43, 44, 
            166, 166, 166, 45, 46, 166, 47, 48, 166, 166, 
            166, 49, 50, 166, 51, 52, 166, 166, 166, 53, 
            54, 166, 55, 56, 57, 166, 58, 59, 60, 166, 
            61, 62, 166, 166, 166, 63, 64, 166, 65, 66, 
            166, 166, 166, 67, 68, 166, 69, 70, 166, 166, 
            166, 71, 72, 166, 73, 74, 75, 166, 76, 77, 
            78, 166, 79, 80, 166, 166, 166, 81, 82, 166, 
            83, 84, 166, 166, 166, 85, 86, 166, 166, 87, 
            166, 166, 88, 89, 90, 166, 91, 166, 92, 166, 
            93, 94, 95, 166, 96, 97, 166, 166, 98, 99, 
            100, 166, 101, 102, 103, 166, 166, 104, 166, 166, 
            105, 106, 107, 166, 108, 109, 110, 166, 111, 112, 
            113, 166, 114, 115, 116, 166, 117, 118, 166, 166, 
            119, 120, 121, 166, 122, 123, 124, 166, 125, 126, 
            127, 166, 128, 129, 166, 166, 130, 131, 132, 166, 
            133, 134, 135, 166, 136, 137, 138, 166, 139, 140, 
            166, 166, 166, 141, 142, 166, 143, 144, 166, 166, 
            166, 145, 146, 166, 147, 148, 166, 166, 149, 150, 
            151, 166, 152, 153, 154, 166, 155, 156, 157, 166, 
            158, 159, 166, 166, 166, 160, 161, 166, 162, 163, 
            166, 166, 166, 164, 165, 166
        ];
        InterruptModeStepTable = [14];
    }
}
