//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;

namespace MrKWatkins.OakCpu.M6502;

public sealed unsafe partial class M6502StepEmulator
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void ExecuteOverlap()
    {
        if (overlapPipeline == default)
        {
            return;
        }

        delegate*<M6502StepEmulator, void> overlap = overlapPipeline;
        overlapPipeline = default;
        overlap(this);
    }

    private ushort SerializeOverlapPipeline()
    {
        if (overlapPipeline == default)
        {
            return 0;
        }

        for (var index = 1; index < Overlaps.Length; index++)
        {
            if ((nuint)Overlaps[index] == (nuint)overlapPipeline)
            {
                return (ushort)index;
            }
        }

        throw new InvalidOperationException("Unknown overlap pipeline.");
    }

    private void RestoreOverlapPipeline(ushort overlapIndex)
    {
        if (overlapIndex >= Overlaps.Length)
        {
            throw new InvalidOperationException("Unknown overlap pipeline.");
        }

        overlapPipeline = Overlaps[overlapIndex];
    }

    // Overlap 0xEA: NOP [0]
    private static void Overlap0(M6502StepEmulator emulator)
    {
    }
}
