//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;

namespace MrKWatkins.OakCpu.M6502;

internal sealed class M6502InstructionInterrupts : M6502Interrupts
{
    private readonly M6502InstructionEmulator emulator;

    internal M6502InstructionInterrupts(M6502InstructionEmulator emulator)
    {
        this.emulator = emulator;
    }

    public override bool IRQ
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.irq; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.SetIRQ(value);
    }

    public override bool NMI
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.nmi; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.SetNMI(value);
    }
}
