//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace MrKWatkins.OakCpu.M6502;

public sealed unsafe partial class M6502InstructionEmulator
{
    private const ushort OpcodeReadStep0 = 0;

    private static int Error(M6502InstructionEmulator emulator, Action<ActionRequired, ushort, byte> onActionRequired)
    {
        throw new NotSupportedException("Opcode not supported");
    }

    // Opcode read
    private static int Opcode_read(M6502InstructionEmulator emulator, Action<ActionRequired, ushort, byte> onActionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        onActionRequired(ActionRequired.OpcodeRead, emulator.address, emulator.data);
        ushort nextInstruction1 = 65535;
        nextInstruction1 = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(emulator.opcodeStepTable), emulator.data);
        if (nextInstruction1 != 65535)
        {
            return 2 + emulator.ExecuteDecodedInstruction(nextInstruction1, onActionRequired);
        }

        return 2;
    }

    // Halt cycle
    private static int Halt_cycle(M6502InstructionEmulator emulator, Action<ActionRequired, ushort, byte> onActionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        onActionRequired(ActionRequired.OpcodeRead, emulator.address, emulator.data);
        ushort nextInstruction3 = 65535;
        nextInstruction3 = Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(emulator.opcodeStepTable), emulator.data);
        if (nextInstruction3 != 65535)
        {
            return 2 + emulator.ExecuteDecodedInstruction(nextInstruction3, onActionRequired);
        }

        emulator.nextSequenceStep = 1;
        return 2;
    }

    // Interrupt Mode 0
    private static int Interrupt_Mode_0(M6502InstructionEmulator emulator, Action<ActionRequired, ushort, byte> onActionRequired)
    {
        return 1;
    }

    // LDA #n
    private static int LDA_n(M6502InstructionEmulator emulator, Action<ActionRequired, ushort, byte> onActionRequired)
    {
        emulator.address = emulator.PC;
        emulator.PC += 0x01;
        onActionRequired(ActionRequired.MemoryRead, emulator.address, emulator.data);
        emulator.A = emulator.data;

        // Update flags.
        int flags = emulator.P & 0b01011101; // Copy flag.C, flag.I, flag.D, flag.B and V from P.
        flags |= (Unsafe.BitCast<bool, byte>(emulator.A == 0)) << 1; // Set Z if is_zero(A) is true.
        flags |= emulator.A & 0b10000000; // Set N if is_negative(A) is true.
        emulator.P = (byte)flags;
        return 2;
    }

    // NOP
    private static int NOP(M6502InstructionEmulator emulator, Action<ActionRequired, ushort, byte> onActionRequired)
    {
        return 0;
    }
}
