//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;

namespace MrKWatkins.OakCpu.M6502;

internal sealed class M6502InstructionRegisters : M6502Registers
{
    private readonly M6502InstructionEmulator emulator;

    internal M6502InstructionRegisters(M6502InstructionEmulator emulator)
    {
        this.emulator = emulator;
    }

    public override byte A
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.A; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.A = value;
    }

    public override byte P
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.P; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.P = value;
    }

    public override ushort PC
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.PC; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.PC = value;
    }

    public override byte S
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.S; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.S = value;
    }

    public override byte X
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.X; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.X = value;
    }

    public override byte Y
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => emulator.Y; 
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set => emulator.Y = value;
    }
}
