//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace MrKWatkins.OakCpu.M6502;
/// <summary>
/// Provides access to the M6502 interrupt state.
/// </summary>
public abstract class M6502Interrupts
{
    /// <summary>
    /// Gets or sets whether the external IRQ line is asserted.
    /// </summary>
    public abstract bool IRQ { get; set; }

    /// <summary>
    /// Gets or sets whether the external NMI line is asserted.
    /// </summary>
    public abstract bool NMI { get; set; }
}
