//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace MrKWatkins.OakCpu.M6502;

internal unsafe readonly struct Step(delegate*<M6502StepEmulator, ref ActionRequired, void> handler, ushort nextStep, ActionRequired actionRequired, delegate*<M6502StepEmulator, void> overlap)
{
    internal readonly delegate*<M6502StepEmulator, ref ActionRequired, void> Handler = handler;

    internal readonly ushort NextStep = nextStep;

    internal readonly ActionRequired ActionRequired = actionRequired;

    internal readonly delegate*<M6502StepEmulator, void> Overlap = overlap;
}
